package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PaetReRecomendacion generated by hbm2java
 */
public class PaetReRecomendacion  implements java.io.Serializable {


     private BigDecimal reCodigo;
     private PaetPgProcesoSeguimiento paetPgProcesoSeguimiento;
     private Date reFechaLimite;
     private Date reFechaRealizada;
     private String reDescripcion;
     private char reEstado;

    public PaetReRecomendacion() {
    }

	
    public PaetReRecomendacion(BigDecimal reCodigo, PaetPgProcesoSeguimiento paetPgProcesoSeguimiento, Date reFechaLimite, String reDescripcion, char reEstado) {
        this.reCodigo = reCodigo;
        this.paetPgProcesoSeguimiento = paetPgProcesoSeguimiento;
        this.reFechaLimite = reFechaLimite;
        this.reDescripcion = reDescripcion;
        this.reEstado = reEstado;
    }
    public PaetReRecomendacion(BigDecimal reCodigo, PaetPgProcesoSeguimiento paetPgProcesoSeguimiento, Date reFechaLimite, Date reFechaRealizada, String reDescripcion, char reEstado) {
       this.reCodigo = reCodigo;
       this.paetPgProcesoSeguimiento = paetPgProcesoSeguimiento;
       this.reFechaLimite = reFechaLimite;
       this.reFechaRealizada = reFechaRealizada;
       this.reDescripcion = reDescripcion;
       this.reEstado = reEstado;
    }
   
    public BigDecimal getReCodigo() {
        return this.reCodigo;
    }
    
    public void setReCodigo(BigDecimal reCodigo) {
        this.reCodigo = reCodigo;
    }
    public PaetPgProcesoSeguimiento getPaetPgProcesoSeguimiento() {
        return this.paetPgProcesoSeguimiento;
    }
    
    public void setPaetPgProcesoSeguimiento(PaetPgProcesoSeguimiento paetPgProcesoSeguimiento) {
        this.paetPgProcesoSeguimiento = paetPgProcesoSeguimiento;
    }
    public Date getReFechaLimite() {
        return this.reFechaLimite;
    }
    
    public void setReFechaLimite(Date reFechaLimite) {
        this.reFechaLimite = reFechaLimite;
    }
    public Date getReFechaRealizada() {
        return this.reFechaRealizada;
    }
    
    public void setReFechaRealizada(Date reFechaRealizada) {
        this.reFechaRealizada = reFechaRealizada;
    }
    public String getReDescripcion() {
        return this.reDescripcion;
    }
    
    public void setReDescripcion(String reDescripcion) {
        this.reDescripcion = reDescripcion;
    }
    public char getReEstado() {
        return this.reEstado;
    }
    
    public void setReEstado(char reEstado) {
        this.reEstado = reEstado;
    }




}


