package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaetCnCanton generated by hbm2java
 */
public class PaetCnCanton  implements java.io.Serializable {


     private byte cnCodigo;
     private PaetPrProvincia paetPrProvincia;
     private String cnDescripcion;
     private Set paetDsDistritos = new HashSet(0);

    public PaetCnCanton() {
    }

	
    public PaetCnCanton(byte cnCodigo, PaetPrProvincia paetPrProvincia, String cnDescripcion) {
        this.cnCodigo = cnCodigo;
        this.paetPrProvincia = paetPrProvincia;
        this.cnDescripcion = cnDescripcion;
    }
    public PaetCnCanton(byte cnCodigo, PaetPrProvincia paetPrProvincia, String cnDescripcion, Set paetDsDistritos) {
       this.cnCodigo = cnCodigo;
       this.paetPrProvincia = paetPrProvincia;
       this.cnDescripcion = cnDescripcion;
       this.paetDsDistritos = paetDsDistritos;
    }
   
    public byte getCnCodigo() {
        return this.cnCodigo;
    }
    
    public void setCnCodigo(byte cnCodigo) {
        this.cnCodigo = cnCodigo;
    }
    public PaetPrProvincia getPaetPrProvincia() {
        return this.paetPrProvincia;
    }
    
    public void setPaetPrProvincia(PaetPrProvincia paetPrProvincia) {
        this.paetPrProvincia = paetPrProvincia;
    }
    public String getCnDescripcion() {
        return this.cnDescripcion;
    }
    
    public void setCnDescripcion(String cnDescripcion) {
        this.cnDescripcion = cnDescripcion;
    }
    public Set getPaetDsDistritos() {
        return this.paetDsDistritos;
    }
    
    public void setPaetDsDistritos(Set paetDsDistritos) {
        this.paetDsDistritos = paetDsDistritos;
    }




}


