package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetTlTelefono generated by hbm2java
 */
public class PaetTlTelefono  implements java.io.Serializable {


     private BigDecimal tlCodigo;
     private PaetTrTrabajador paetTrTrabajador;
     private String tlTelefono;
     private String tlDescripcion;
     private char tlEstado;

    public PaetTlTelefono() {
    }

    public PaetTlTelefono(BigDecimal tlCodigo, PaetTrTrabajador paetTrTrabajador, String tlTelefono, String tlDescripcion, char tlEstado) {
       this.tlCodigo = tlCodigo;
       this.paetTrTrabajador = paetTrTrabajador;
       this.tlTelefono = tlTelefono;
       this.tlDescripcion = tlDescripcion;
       this.tlEstado = tlEstado;
    }
   
    public BigDecimal getTlCodigo() {
        return this.tlCodigo;
    }
    
    public void setTlCodigo(BigDecimal tlCodigo) {
        this.tlCodigo = tlCodigo;
    }
    public PaetTrTrabajador getPaetTrTrabajador() {
        return this.paetTrTrabajador;
    }
    
    public void setPaetTrTrabajador(PaetTrTrabajador paetTrTrabajador) {
        this.paetTrTrabajador = paetTrTrabajador;
    }
    public String getTlTelefono() {
        return this.tlTelefono;
    }
    
    public void setTlTelefono(String tlTelefono) {
        this.tlTelefono = tlTelefono;
    }
    public String getTlDescripcion() {
        return this.tlDescripcion;
    }
    
    public void setTlDescripcion(String tlDescripcion) {
        this.tlDescripcion = tlDescripcion;
    }
    public char getTlEstado() {
        return this.tlEstado;
    }
    
    public void setTlEstado(char tlEstado) {
        this.tlEstado = tlEstado;
    }




}


