package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetAcCaActCaract generated by hbm2java
 */
public class PaetAcCaActCaract  implements java.io.Serializable {


     private BigDecimal acCaCodigo;
     private BigDecimal acActividad;
     private BigDecimal caCaracteristica;
     private char acCaTeletrabajable;

    public PaetAcCaActCaract() {
    }

    public PaetAcCaActCaract(BigDecimal acCaCodigo, BigDecimal acActividad, BigDecimal caCaracteristica, char acCaTeletrabajable) {
       this.acCaCodigo = acCaCodigo;
       this.acActividad = acActividad;
       this.caCaracteristica = caCaracteristica;
       this.acCaTeletrabajable = acCaTeletrabajable;
    }
   
    public BigDecimal getAcCaCodigo() {
        return this.acCaCodigo;
    }
    
    public void setAcCaCodigo(BigDecimal acCaCodigo) {
        this.acCaCodigo = acCaCodigo;
    }
    
    public BigDecimal getAcActividad() {
        return this.acActividad;
    }
    
    public void setAcActividad(BigDecimal acActividad) {
        this.acActividad = acActividad;
    }
    
    public BigDecimal getCaCaracteristica() {
        return this.caCaracteristica;
    }
    
    public void setCaCaracteristica(BigDecimal caCaracteristica) {
        this.caCaracteristica = caCaracteristica;
    }
    
    public char getAcCaTeletrabajable() {
        return this.acCaTeletrabajable;
    }
    
    public void setAcCaTeletrabajable(char acCaTeletrabajable) {
        this.acCaTeletrabajable = acCaTeletrabajable;
    }
}


