package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetEsEstado generated by hbm2java
 */
public class PaetEsEstado  implements java.io.Serializable {


     private BigDecimal esCodigo;
     private BigDecimal esSecuencia;
     private String esDescripcion;
     private char esProceso;
     private Set paetPgProcesoSeguimientos = new HashSet(0);
     private Set paetPsProcesoSolicituds = new HashSet(0);
     private Set paetPfProcesoFinalizacions = new HashSet(0);

    public PaetEsEstado() {
    }

	
    public PaetEsEstado(BigDecimal esCodigo, BigDecimal esSecuencia, String esDescripcion, char esProceso) {
        this.esCodigo = esCodigo;
        this.esSecuencia = esSecuencia;
        this.esDescripcion = esDescripcion;
        this.esProceso = esProceso;
    }
    public PaetEsEstado(BigDecimal esCodigo, BigDecimal esSecuencia, String esDescripcion, char esProceso, Set paetPgProcesoSeguimientos, Set paetPsProcesoSolicituds, Set paetPfProcesoFinalizacions) {
       this.esCodigo = esCodigo;
       this.esSecuencia = esSecuencia;
       this.esDescripcion = esDescripcion;
       this.esProceso = esProceso;
       this.paetPgProcesoSeguimientos = paetPgProcesoSeguimientos;
       this.paetPsProcesoSolicituds = paetPsProcesoSolicituds;
       this.paetPfProcesoFinalizacions = paetPfProcesoFinalizacions;
    }
   
    public BigDecimal getEsCodigo() {
        return this.esCodigo;
    }
    
    public void setEsCodigo(BigDecimal esCodigo) {
        this.esCodigo = esCodigo;
    }
    public BigDecimal getEsSecuencia() {
        return this.esSecuencia;
    }
    
    public void setEsSecuencia(BigDecimal esSecuencia) {
        this.esSecuencia = esSecuencia;
    }
    public String getEsDescripcion() {
        return this.esDescripcion;
    }
    
    public void setEsDescripcion(String esDescripcion) {
        this.esDescripcion = esDescripcion;
    }
    public char getEsProceso() {
        return this.esProceso;
    }
    
    public void setEsProceso(char esProceso) {
        this.esProceso = esProceso;
    }
    public Set getPaetPgProcesoSeguimientos() {
        return this.paetPgProcesoSeguimientos;
    }
    
    public void setPaetPgProcesoSeguimientos(Set paetPgProcesoSeguimientos) {
        this.paetPgProcesoSeguimientos = paetPgProcesoSeguimientos;
    }
    public Set getPaetPsProcesoSolicituds() {
        return this.paetPsProcesoSolicituds;
    }
    
    public void setPaetPsProcesoSolicituds(Set paetPsProcesoSolicituds) {
        this.paetPsProcesoSolicituds = paetPsProcesoSolicituds;
    }
    public Set getPaetPfProcesoFinalizacions() {
        return this.paetPfProcesoFinalizacions;
    }
    
    public void setPaetPfProcesoFinalizacions(Set paetPfProcesoFinalizacions) {
        this.paetPfProcesoFinalizacions = paetPfProcesoFinalizacions;
    }




}


