package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetMtMeta generated by hbm2java
 */
public class PaetMtMeta  implements java.io.Serializable {


     private BigDecimal mtCodigo;
     private String mtDescripcion;
     private short mtLimite;
     private short mtPeso;
     private short mtLimiteSobresaliente;
     private short mtLimiteBajo;
     private short mtPorcentajeSobresaliente;
     private short mtPorcentajeBajo;
     private String mtComentario;
     private BigDecimal evEvaluacion;
     private short mtLogroAlcanzado;
     private short mtPorcentajeAlcanzado;

    public PaetMtMeta() {
    }

	
    public PaetMtMeta(BigDecimal mtCodigo, String mtDescripcion, short mtLimite, short mtPeso, short mtLimiteSobresaliente, short mtLimiteBajo, short mtPorcentajeSobresaliente, short mtPorcentajeBajo, BigDecimal evEvaluacion, short mtLogroAlcanzado, short mtPorcentajeAlcanzado) {
        this.mtCodigo = mtCodigo;
        this.mtDescripcion = mtDescripcion;
        this.mtLimite = mtLimite;
        this.mtPeso = mtPeso;
        this.mtLimiteSobresaliente = mtLimiteSobresaliente;
        this.mtLimiteBajo = mtLimiteBajo;
        this.mtPorcentajeSobresaliente = mtPorcentajeSobresaliente;
        this.mtPorcentajeBajo = mtPorcentajeBajo;
        this.evEvaluacion = evEvaluacion;
        this.mtLogroAlcanzado = mtLogroAlcanzado;
        this.mtPorcentajeAlcanzado = mtPorcentajeAlcanzado;
        
    }
   
    public BigDecimal getMtCodigo() {
        return this.mtCodigo;
    }
    
    public void setMtCodigo(BigDecimal mtCodigo) {
        this.mtCodigo = mtCodigo;
    }
    
    public String getMtDescripcion() {
        return this.mtDescripcion;
    }
    
    public void setMtDescripcion(String mtDescripcion) {
        this.mtDescripcion = mtDescripcion;
    }
    public short getMtLimite() {
        return this.mtLimite;
    }
    
    public void setMtLimite(short mtLimite) {
        this.mtLimite = mtLimite;
    }
    public short getMtPeso() {
        return this.mtPeso;
    }
    
    public void setMtPeso(short mtPeso) {
        this.mtPeso = mtPeso;
    }
    public short getMtLimiteSobresaliente() {
        return this.mtLimiteSobresaliente;
    }
    
    public void setMtLimiteSobresaliente(short mtLimiteSobresaliente) {
        this.mtLimiteSobresaliente = mtLimiteSobresaliente;
    }
    public short getMtLimiteBajo() {
        return this.mtLimiteBajo;
    }
    
    public void setMtLimiteBajo(short mtLimiteBajo) {
        this.mtLimiteBajo = mtLimiteBajo;
    }
    public short getMtPorcentajeSobresaliente() {
        return this.mtPorcentajeSobresaliente;
    }
    
    public void setMtPorcentajeSobresaliente(short mtPorcentajeSobresaliente) {
        this.mtPorcentajeSobresaliente = mtPorcentajeSobresaliente;
    }
    public short getMtPorcentajeBajo() {
        return this.mtPorcentajeBajo;
    }
    
    public void setMtPorcentajeBajo(short mtPorcentajeBajo) {
        this.mtPorcentajeBajo = mtPorcentajeBajo;
    }
    public String getMtComentario() {
        return this.mtComentario;
    }
    
    public void setMtComentario(String mtComentario) {
        this.mtComentario = mtComentario;
    }
    
    public BigDecimal getEvEvaluacion() {
        return this.evEvaluacion;
    }
    
    public void setEvEvaluacion(BigDecimal evEvaluacion) {
        this.evEvaluacion = evEvaluacion;
    }
    
    public short getMtLogroAlcanzado() {
        return this.mtLogroAlcanzado;
    }
    
    public void setMtLogroAlcanzado(short mtLogroAlcanzado) {
        this.mtLogroAlcanzado = mtLogroAlcanzado;
    }
    
    public short getMtPorcentajeAlcanzado() {
        return this.mtPorcentajeAlcanzado;
    }
    
    public void setMtPorcentajeAlcanzado(short mtPorcentajeAlcanzado) {
        this.mtPorcentajeAlcanzado = mtPorcentajeAlcanzado;
    }
}


