package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetPsProcesoSolicitud generated by hbm2java
 */
public class PaetPsProcesoSolicitud  implements java.io.Serializable {


     private BigDecimal psCodigo;
     private PaetSlSolicitud paetSlSolicitud;
     private PaetEsEstado paetEsEstado;
     private Date psFecha;
     private String psObservacion;
     private Set paetAnAnalisisPuestos = new HashSet(0);

    public PaetPsProcesoSolicitud() {
    }

	
    public PaetPsProcesoSolicitud(BigDecimal psCodigo, PaetSlSolicitud paetSlSolicitud, PaetEsEstado paetEsEstado, Date psFecha, String psObservacion) {
        this.psCodigo = psCodigo;
        this.paetSlSolicitud = paetSlSolicitud;
        this.paetEsEstado = paetEsEstado;
        this.psFecha = psFecha;
        this.psObservacion = psObservacion;
    }
    public PaetPsProcesoSolicitud(BigDecimal psCodigo, PaetSlSolicitud paetSlSolicitud, PaetEsEstado paetEsEstado, Date psFecha, String psObservacion, Set paetAnAnalisisPuestos) {
       this.psCodigo = psCodigo;
       this.paetSlSolicitud = paetSlSolicitud;
       this.paetEsEstado = paetEsEstado;
       this.psFecha = psFecha;
       this.psObservacion = psObservacion;
       this.paetAnAnalisisPuestos = paetAnAnalisisPuestos;
    }
   
    public BigDecimal getPsCodigo() {
        return this.psCodigo;
    }
    
    public void setPsCodigo(BigDecimal psCodigo) {
        this.psCodigo = psCodigo;
    }
    public PaetSlSolicitud getPaetSlSolicitud() {
        return this.paetSlSolicitud;
    }
    
    public void setPaetSlSolicitud(PaetSlSolicitud paetSlSolicitud) {
        this.paetSlSolicitud = paetSlSolicitud;
    }
    public PaetEsEstado getPaetEsEstado() {
        return this.paetEsEstado;
    }
    
    public void setPaetEsEstado(PaetEsEstado paetEsEstado) {
        this.paetEsEstado = paetEsEstado;
    }
    public Date getPsFecha() {
        return this.psFecha;
    }
    
    public void setPsFecha(Date psFecha) {
        this.psFecha = psFecha;
    }
    public String getPsObservacion() {
        return this.psObservacion;
    }
    
    public void setPsObservacion(String psObservacion) {
        this.psObservacion = psObservacion;
    }
    public Set getPaetAnAnalisisPuestos() {
        return this.paetAnAnalisisPuestos;
    }
    
    public void setPaetAnAnalisisPuestos(Set paetAnAnalisisPuestos) {
        this.paetAnAnalisisPuestos = paetAnAnalisisPuestos;
    }




}


