package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetCuCausa generated by hbm2java
 */
public class PaetCuCausa  implements java.io.Serializable {


     private BigDecimal cuCodigo;
     private String cuDescripcion;
     private BigDecimal evEvaluacion;

    public PaetCuCausa() {
    }

    public PaetCuCausa(BigDecimal cuCodigo, String cuDescripcion, BigDecimal evEvaluacion) {
       this.cuCodigo = cuCodigo;
       this.cuDescripcion = cuDescripcion;
       this.evEvaluacion = evEvaluacion;
    }
   
    public BigDecimal getCuCodigo() {
        return this.cuCodigo;
    }
    
    public void setCuCodigo(BigDecimal cuCodigo) {
        this.cuCodigo = cuCodigo;
    }
    
    public String getCuDescripcion() {
        return this.cuDescripcion;
    }
    
    public void setCuDescripcion(String cuDescripcion) {
        this.cuDescripcion = cuDescripcion;
    }

    public BigDecimal getEvEvaluacion() {
        return this.evEvaluacion;
    }
    
    public void setEvEvaluacion(BigDecimal evEvaluacion) {
        this.evEvaluacion = evEvaluacion;
    }
}


