package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetPgProcesoSeguimiento generated by hbm2java
 */
public class PaetPgProcesoSeguimiento  implements java.io.Serializable {


     private BigDecimal pgCodigo;
     private PaetEsEstado paetEsEstado;
     private PaetTtTeletrabajador paetTtTeletrabajador;
     private Date pgFecha;
     private BigDecimal pgNumero;
     private String pgObservacion;
     private Set paetEvEvaluacions = new HashSet(0);
     private Set paetReRecomendacions = new HashSet(0);

    public PaetPgProcesoSeguimiento() {
    }

	
    public PaetPgProcesoSeguimiento(BigDecimal pgCodigo, PaetEsEstado paetEsEstado, PaetTtTeletrabajador paetTtTeletrabajador, Date pgFecha, BigDecimal pgNumero) {
        this.pgCodigo = pgCodigo;
        this.paetEsEstado = paetEsEstado;
        this.paetTtTeletrabajador = paetTtTeletrabajador;
        this.pgFecha = pgFecha;
        this.pgNumero = pgNumero;
    }
    public PaetPgProcesoSeguimiento(BigDecimal pgCodigo, PaetEsEstado paetEsEstado, PaetTtTeletrabajador paetTtTeletrabajador, Date pgFecha, BigDecimal pgNumero, String pgObservacion, Set paetEvEvaluacions, Set paetReRecomendacions) {
       this.pgCodigo = pgCodigo;
       this.paetEsEstado = paetEsEstado;
       this.paetTtTeletrabajador = paetTtTeletrabajador;
       this.pgFecha = pgFecha;
       this.pgNumero = pgNumero;
       this.pgObservacion = pgObservacion;
       this.paetEvEvaluacions = paetEvEvaluacions;
       this.paetReRecomendacions = paetReRecomendacions;
    }
   
    public BigDecimal getPgCodigo() {
        return this.pgCodigo;
    }
    
    public void setPgCodigo(BigDecimal pgCodigo) {
        this.pgCodigo = pgCodigo;
    }
    public PaetEsEstado getPaetEsEstado() {
        return this.paetEsEstado;
    }
    
    public void setPaetEsEstado(PaetEsEstado paetEsEstado) {
        this.paetEsEstado = paetEsEstado;
    }
    public PaetTtTeletrabajador getPaetTtTeletrabajador() {
        return this.paetTtTeletrabajador;
    }
    
    public void setPaetTtTeletrabajador(PaetTtTeletrabajador paetTtTeletrabajador) {
        this.paetTtTeletrabajador = paetTtTeletrabajador;
    }
    public Date getPgFecha() {
        return this.pgFecha;
    }
    
    public void setPgFecha(Date pgFecha) {
        this.pgFecha = pgFecha;
    }
    public BigDecimal getPgNumero() {
        return this.pgNumero;
    }
    
    public void setPgNumero(BigDecimal pgNumero) {
        this.pgNumero = pgNumero;
    }
    public String getPgObservacion() {
        return this.pgObservacion;
    }
    
    public void setPgObservacion(String pgObservacion) {
        this.pgObservacion = pgObservacion;
    }
    public Set getPaetEvEvaluacions() {
        return this.paetEvEvaluacions;
    }
    
    public void setPaetEvEvaluacions(Set paetEvEvaluacions) {
        this.paetEvEvaluacions = paetEvEvaluacions;
    }
    public Set getPaetReRecomendacions() {
        return this.paetReRecomendacions;
    }
    
    public void setPaetReRecomendacions(Set paetReRecomendacions) {
        this.paetReRecomendacions = paetReRecomendacions;
    }




}


