package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetMtMeta generated by hbm2java
 */
public class PaetMtMeta  implements java.io.Serializable {


     private BigDecimal mtCodigo;
     private String mtDescripcion;
     private BigDecimal mtLimite;
     private BigDecimal mtPeso;
     private BigDecimal mtLimiteSobresaliente;
     private BigDecimal mtLimiteBajo;
     private BigDecimal mtPorcentajeSobresaliente;
     private BigDecimal mtPorcentajeBajo;
     private BigDecimal evEvaluacion;
     private BigDecimal mtLogroAlcanzado;
     private BigDecimal mtPorcentajeAlcanzado;

    public PaetMtMeta() {
    }

	
    public PaetMtMeta(BigDecimal mtCodigo, String mtDescripcion, BigDecimal mtLimite, BigDecimal mtPeso, BigDecimal mtLimiteSobresaliente, BigDecimal mtLimiteBajo, BigDecimal mtPorcentajeSobresaliente, BigDecimal mtPorcentajeBajo, BigDecimal evEvaluacion, BigDecimal mtLogroAlcanzado, BigDecimal mtPorcentajeAlcanzado) {
        this.mtCodigo = mtCodigo;
        this.mtDescripcion = mtDescripcion;
        this.mtLimite = mtLimite;
        this.mtPeso = mtPeso;
        this.mtLimiteSobresaliente = mtLimiteSobresaliente;
        this.mtLimiteBajo = mtLimiteBajo;
        this.mtPorcentajeSobresaliente = mtPorcentajeSobresaliente;
        this.mtPorcentajeBajo = mtPorcentajeBajo;
        this.evEvaluacion = evEvaluacion;
        this.mtLogroAlcanzado = mtLogroAlcanzado;
        this.mtPorcentajeAlcanzado = mtPorcentajeAlcanzado;
        
    }
   
    public BigDecimal getMtCodigo() {
        return this.mtCodigo;
    }
    
    public void setMtCodigo(BigDecimal mtCodigo) {
        this.mtCodigo = mtCodigo;
    }
    
    public String getMtDescripcion() {
        return this.mtDescripcion;
    }
    
    public void setMtDescripcion(String mtDescripcion) {
        this.mtDescripcion = mtDescripcion;
    }
    public BigDecimal getMtLimite() {
        return this.mtLimite;
    }
    
    public void setMtLimite(BigDecimal mtLimite) {
        this.mtLimite = mtLimite;
    }
    public BigDecimal getMtPeso() {
        return this.mtPeso;
    }
    
    public void setMtPeso(BigDecimal mtPeso) {
        this.mtPeso = mtPeso;
    }
    public BigDecimal getMtLimiteSobresaliente() {
        return this.mtLimiteSobresaliente;
    }
    
    public void setMtLimiteSobresaliente(BigDecimal mtLimiteSobresaliente) {
        this.mtLimiteSobresaliente = mtLimiteSobresaliente;
    }
    public BigDecimal getMtLimiteBajo() {
        return this.mtLimiteBajo;
    }
    
    public void setMtLimiteBajo(BigDecimal mtLimiteBajo) {
        this.mtLimiteBajo = mtLimiteBajo;
    }
    public BigDecimal getMtPorcentajeSobresaliente() {
        return this.mtPorcentajeSobresaliente;
    }
    
    public void setMtPorcentajeSobresaliente(BigDecimal mtPorcentajeSobresaliente) {
        this.mtPorcentajeSobresaliente = mtPorcentajeSobresaliente;
    }
    public BigDecimal getMtPorcentajeBajo() {
        return this.mtPorcentajeBajo;
    }
    
    public void setMtPorcentajeBajo(BigDecimal mtPorcentajeBajo) {
        this.mtPorcentajeBajo = mtPorcentajeBajo;
    }
    
    public BigDecimal getEvEvaluacion() {
        return this.evEvaluacion;
    }
    
    public void setEvEvaluacion(BigDecimal evEvaluacion) {
        this.evEvaluacion = evEvaluacion;
    }
    
    public BigDecimal getMtLogroAlcanzado() {
        return this.mtLogroAlcanzado;
    }
    
    public void setMtLogroAlcanzado(BigDecimal mtLogroAlcanzado) {
        this.mtLogroAlcanzado = mtLogroAlcanzado;
    }
    
    public BigDecimal getMtPorcentajeAlcanzado() {
        return this.mtPorcentajeAlcanzado;
    }
    
    public void setMtPorcentajeAlcanzado(BigDecimal mtPorcentajeAlcanzado) {
        this.mtPorcentajeAlcanzado = mtPorcentajeAlcanzado;
    }
}


