package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetTlTelefono generated by hbm2java
 */
public class PaetTlTelefono  implements java.io.Serializable {


     private BigDecimal tlCodigo;
     private String tlTelefono;
     private String tlDescripcion;
     private char tlEstado;
     private String trTrabajador;

    public PaetTlTelefono() {
    }

    public PaetTlTelefono(BigDecimal tlCodigo, String tlTelefono, String tlDescripcion, char tlEstado, String trTrabajador) {
       this.tlCodigo = tlCodigo;
       this.tlTelefono = tlTelefono;
       this.tlDescripcion = tlDescripcion;
       this.tlEstado = tlEstado;
       this.trTrabajador = trTrabajador;
    }
   
    public BigDecimal getTlCodigo() {
        return this.tlCodigo;
    }
    
    public void setTlCodigo(BigDecimal tlCodigo) {
        this.tlCodigo = tlCodigo;
    }
    
    public String getTlTelefono() {
        return this.tlTelefono;
    }
    
    public void setTlTelefono(String tlTelefono) {
        this.tlTelefono = tlTelefono;
    }
    
    public String getTlDescripcion() {
        return this.tlDescripcion;
    }
    
    public void setTlDescripcion(String tlDescripcion) {
        this.tlDescripcion = tlDescripcion;
    }
    
    public char getTlEstado() {
        return this.tlEstado;
    }
    
    public void setTlEstado(char tlEstado) {
        this.tlEstado = tlEstado;
    }

    public String getTrTrabajador() {
        return this.trTrabajador;
    }
    
    public void setTrTrabajador(String trTrabajador) {
        this.trTrabajador = trTrabajador;
    }
}


