package PAET_DOMAIN;
// Generated 13-oct-2016 20:16:04 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetArArea generated by hbm2java
 */
public class PaetArArea  implements java.io.Serializable {


     private BigDecimal arCodigo;
     private PaetDrDireccion paetDrDireccion;
     private String arDescripcion;
     private char arEstado;
     private Set paetPtPuestos = new HashSet(0);

    public PaetArArea() {
    }

	
    public PaetArArea(BigDecimal arCodigo, PaetDrDireccion paetDrDireccion, String arDescripcion, char arEstado) {
        this.arCodigo = arCodigo;
        this.paetDrDireccion = paetDrDireccion;
        this.arDescripcion = arDescripcion;
        this.arEstado = arEstado;
    }
    public PaetArArea(BigDecimal arCodigo, PaetDrDireccion paetDrDireccion, String arDescripcion, char arEstado, Set paetPtPuestos) {
       this.arCodigo = arCodigo;
       this.paetDrDireccion = paetDrDireccion;
       this.arDescripcion = arDescripcion;
       this.arEstado = arEstado;
       this.paetPtPuestos = paetPtPuestos;
    }
   
    public BigDecimal getArCodigo() {
        return this.arCodigo;
    }
    
    public void setArCodigo(BigDecimal arCodigo) {
        this.arCodigo = arCodigo;
    }
    public PaetDrDireccion getPaetDrDireccion() {
        return this.paetDrDireccion;
    }
    
    public void setPaetDrDireccion(PaetDrDireccion paetDrDireccion) {
        this.paetDrDireccion = paetDrDireccion;
    }
    public String getArDescripcion() {
        return this.arDescripcion;
    }
    
    public void setArDescripcion(String arDescripcion) {
        this.arDescripcion = arDescripcion;
    }
    public char getArEstado() {
        return this.arEstado;
    }
    
    public void setArEstado(char arEstado) {
        this.arEstado = arEstado;
    }
    public Set getPaetPtPuestos() {
        return this.paetPtPuestos;
    }
    
    public void setPaetPtPuestos(Set paetPtPuestos) {
        this.paetPtPuestos = paetPtPuestos;
    }




}


