package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetTtTeletrabajador generated by hbm2java
 */
public class PaetTtTeletrabajador  implements java.io.Serializable {


     private BigDecimal ttCodigo;
     private PaetTrTrabajador paetTrTrabajador;
     private PaetSlSolicitud paetSlSolicitud;
     private Date ttFechaInicio;
     private Date ttFechaFin;
     private char ttEstado;
     private Set<PaetPgProcesoSeguimiento> paetPgProcesoSeguimientos = new HashSet<PaetPgProcesoSeguimiento>(0);
     private Set<PaetDiTtDiaTeletrabajador> paetDiTtDiaTeletrabajadors = new HashSet<PaetDiTtDiaTeletrabajador>(0);

    public PaetTtTeletrabajador() {
    }

	
    public PaetTtTeletrabajador(BigDecimal ttCodigo, PaetTrTrabajador paetTrTrabajador, PaetSlSolicitud paetSlSolicitud, Date ttFechaInicio, char ttEstado) {
        this.ttCodigo = ttCodigo;
        this.paetTrTrabajador = paetTrTrabajador;
        this.paetSlSolicitud = paetSlSolicitud;
        this.ttFechaInicio = ttFechaInicio;
        this.ttEstado = ttEstado;
    }
    public PaetTtTeletrabajador(BigDecimal ttCodigo, PaetTrTrabajador paetTrTrabajador, PaetSlSolicitud paetSlSolicitud, Date ttFechaInicio, Date ttFechaFin, char ttEstado, Set<PaetPgProcesoSeguimiento> paetPgProcesoSeguimientos, Set<PaetDiTtDiaTeletrabajador> paetDiTtDiaTeletrabajadors) {
       this.ttCodigo = ttCodigo;
       this.paetTrTrabajador = paetTrTrabajador;
       this.paetSlSolicitud = paetSlSolicitud;
       this.ttFechaInicio = ttFechaInicio;
       this.ttFechaFin = ttFechaFin;
       this.ttEstado = ttEstado;
       this.paetPgProcesoSeguimientos = paetPgProcesoSeguimientos;
       this.paetDiTtDiaTeletrabajadors = paetDiTtDiaTeletrabajadors;
    }
   
    public BigDecimal getTtCodigo() {
        return this.ttCodigo;
    }
    
    public void setTtCodigo(BigDecimal ttCodigo) {
        this.ttCodigo = ttCodigo;
    }
    public PaetTrTrabajador getPaetTrTrabajador() {
        return this.paetTrTrabajador;
    }
    
    public void setPaetTrTrabajador(PaetTrTrabajador paetTrTrabajador) {
        this.paetTrTrabajador = paetTrTrabajador;
    }
    public PaetSlSolicitud getPaetSlSolicitud() {
        return this.paetSlSolicitud;
    }
    
    public void setPaetSlSolicitud(PaetSlSolicitud paetSlSolicitud) {
        this.paetSlSolicitud = paetSlSolicitud;
    }
    public Date getTtFechaInicio() {
        return this.ttFechaInicio;
    }
    
    public void setTtFechaInicio(Date ttFechaInicio) {
        this.ttFechaInicio = ttFechaInicio;
    }
    public Date getTtFechaFin() {
        return this.ttFechaFin;
    }
    
    public void setTtFechaFin(Date ttFechaFin) {
        this.ttFechaFin = ttFechaFin;
    }
    public char getTtEstado() {
        return this.ttEstado;
    }
    
    public void setTtEstado(char ttEstado) {
        this.ttEstado = ttEstado;
    }
    public Set<PaetPgProcesoSeguimiento> getPaetPgProcesoSeguimientos() {
        return this.paetPgProcesoSeguimientos;
    }
    
    public void setPaetPgProcesoSeguimientos(Set<PaetPgProcesoSeguimiento> paetPgProcesoSeguimientos) {
        this.paetPgProcesoSeguimientos = paetPgProcesoSeguimientos;
    }
    public Set<PaetDiTtDiaTeletrabajador> getPaetDiTtDiaTeletrabajadors() {
        return this.paetDiTtDiaTeletrabajadors;
    }
    
    public void setPaetDiTtDiaTeletrabajadors(Set<PaetDiTtDiaTeletrabajador> paetDiTtDiaTeletrabajadors) {
        this.paetDiTtDiaTeletrabajadors = paetDiTtDiaTeletrabajadors;
    }




}


