package PAET_DOMAIN;
// Generated 13-oct-2016 20:16:04 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetAcActividad generated by hbm2java
 */
public class PaetAcActividad  implements java.io.Serializable {


     private BigDecimal acCodigo;
     private String acDescripcion;
     private char acEstado;
     private Set paetAcPtActividadPuestos = new HashSet(0);
     private Set paetAcCaActCaracts = new HashSet(0);

    public PaetAcActividad() {
    }

	
    public PaetAcActividad(BigDecimal acCodigo, String acDescripcion, char acEstado) {
        this.acCodigo = acCodigo;
        this.acDescripcion = acDescripcion;
        this.acEstado = acEstado;
    }
    public PaetAcActividad(BigDecimal acCodigo, String acDescripcion, char acEstado, Set paetAcPtActividadPuestos, Set paetAcCaActCaracts) {
       this.acCodigo = acCodigo;
       this.acDescripcion = acDescripcion;
       this.acEstado = acEstado;
       this.paetAcPtActividadPuestos = paetAcPtActividadPuestos;
       this.paetAcCaActCaracts = paetAcCaActCaracts;
    }
   
    public BigDecimal getAcCodigo() {
        return this.acCodigo;
    }
    
    public void setAcCodigo(BigDecimal acCodigo) {
        this.acCodigo = acCodigo;
    }
    public String getAcDescripcion() {
        return this.acDescripcion;
    }
    
    public void setAcDescripcion(String acDescripcion) {
        this.acDescripcion = acDescripcion;
    }
    public char getAcEstado() {
        return this.acEstado;
    }
    
    public void setAcEstado(char acEstado) {
        this.acEstado = acEstado;
    }
    public Set getPaetAcPtActividadPuestos() {
        return this.paetAcPtActividadPuestos;
    }
    
    public void setPaetAcPtActividadPuestos(Set paetAcPtActividadPuestos) {
        this.paetAcPtActividadPuestos = paetAcPtActividadPuestos;
    }
    public Set getPaetAcCaActCaracts() {
        return this.paetAcCaActCaracts;
    }
    
    public void setPaetAcCaActCaracts(Set paetAcCaActCaracts) {
        this.paetAcCaActCaracts = paetAcCaActCaracts;
    }




}


