package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetAnAnalisisPuesto generated by hbm2java
 */
public class PaetAnAnalisisPuesto  implements java.io.Serializable {


     private BigDecimal anCodigo;
     private Short anResultadoFactores;
     private Short anResultadoActividades;
     private Short anResultadoFinal;
     private BigDecimal psProcesoSolicitud;
     private Short anDiasRecomendados;
     private char anModalidad;
     private char anTipoPuesto;

    public PaetAnAnalisisPuesto() {
    }

    public PaetAnAnalisisPuesto(BigDecimal anCodigo, Short anResultadoFactores, Short anResultadoActividades, Short anResultadoFinal, BigDecimal psProcesoSolicitud, Short anDiasRecomendados, char anModalidad, char anTipoPuesto) {
       this.anCodigo = anCodigo;
       this.anResultadoFactores = anResultadoFactores;
       this.anResultadoActividades = anResultadoActividades;
       this.anResultadoFinal = anResultadoFinal;
       this.psProcesoSolicitud = psProcesoSolicitud;
       this.anDiasRecomendados = anDiasRecomendados;
       this.anModalidad = anModalidad;
       this.anTipoPuesto = anTipoPuesto;
    }
   
    public BigDecimal getAnCodigo() {
        return this.anCodigo;
    }
    
    public void setAnCodigo(BigDecimal anCodigo) {
        this.anCodigo = anCodigo;
    }
    
    public Short getAnResultadoFactores() {
        return this.anResultadoFactores;
    }
    
    public void setAnResultadoFactores(Short anResultadoFactores) {
        this.anResultadoFactores = anResultadoFactores;
    }
    public Short getAnResultadoActividades() {
        return this.anResultadoActividades;
    }
    
    public void setAnResultadoActividades(Short anResultadoActividades) {
        this.anResultadoActividades = anResultadoActividades;
    }
    public Short getAnResultadoFinal() {
        return this.anResultadoFinal;
    }
    
    public void setAnResultadoFinal(Short anResultadoFinal) {
        this.anResultadoFinal = anResultadoFinal;
    }
    
    public BigDecimal getPsProcesoSolicitud() {
        return this.psProcesoSolicitud;
    }
    
    public void setPsProcesoSolicitud(BigDecimal psProcesoSolicitud) {
        this.psProcesoSolicitud = psProcesoSolicitud;
    }
    
    public Short getAnDiasRecomendados() {
        return this.anDiasRecomendados;
    }
    
    public void setAnDiasRecomendados(Short anDiasRecomendados) {
        this.anDiasRecomendados = anDiasRecomendados;
    }
    
    public char getAnModalidad() {
        return this.anModalidad;
    }
    
    public void setAnModalidad(char anModalidad) {
        this.anModalidad = anModalidad;
    }
    
    public char getAnTipoPuesto() {
        return this.anTipoPuesto;
    }
    
    public void setAnTipoPuesto(char anTipoPuesto) {
        this.anTipoPuesto = anTipoPuesto;
    }
}


