package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetCrCorreo generated by hbm2java
 */
public class PaetCrCorreo  implements java.io.Serializable {


     private BigDecimal crCodigo;
     private PaetTrTrabajador paetTrTrabajador;
     private String crCorreo;
     private char crEstado;

    public PaetCrCorreo() {
    }

    public PaetCrCorreo(BigDecimal crCodigo, PaetTrTrabajador paetTrTrabajador, String crCorreo, char crEstado) {
       this.crCodigo = crCodigo;
       this.paetTrTrabajador = paetTrTrabajador;
       this.crCorreo = crCorreo;
       this.crEstado = crEstado;
    }
   
    public BigDecimal getCrCodigo() {
        return this.crCodigo;
    }
    
    public void setCrCodigo(BigDecimal crCodigo) {
        this.crCodigo = crCodigo;
    }
    public PaetTrTrabajador getPaetTrTrabajador() {
        return this.paetTrTrabajador;
    }
    
    public void setPaetTrTrabajador(PaetTrTrabajador paetTrTrabajador) {
        this.paetTrTrabajador = paetTrTrabajador;
    }
    public String getCrCorreo() {
        return this.crCorreo;
    }
    
    public void setCrCorreo(String crCorreo) {
        this.crCorreo = crCorreo;
    }
    public char getCrEstado() {
        return this.crEstado;
    }
    
    public void setCrEstado(char crEstado) {
        this.crEstado = crEstado;
    }




}


