package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetDfDireccionFisica generated by hbm2java
 */
public class PaetDfDireccionFisica  implements java.io.Serializable {


     private BigDecimal dfCodigo;
     private PaetTrTrabajador paetTrTrabajador;
     private PaetDsDistrito paetDsDistrito;
     private String dfDireccion;
     private char dfEstado;

    public PaetDfDireccionFisica() {
    }

    public PaetDfDireccionFisica(BigDecimal dfCodigo, PaetTrTrabajador paetTrTrabajador, PaetDsDistrito paetDsDistrito, String dfDireccion, char dfEstado) {
       this.dfCodigo = dfCodigo;
       this.paetTrTrabajador = paetTrTrabajador;
       this.paetDsDistrito = paetDsDistrito;
       this.dfDireccion = dfDireccion;
       this.dfEstado = dfEstado;
    }
   
    public BigDecimal getDfCodigo() {
        return this.dfCodigo;
    }
    
    public void setDfCodigo(BigDecimal dfCodigo) {
        this.dfCodigo = dfCodigo;
    }
    public PaetTrTrabajador getPaetTrTrabajador() {
        return this.paetTrTrabajador;
    }
    
    public void setPaetTrTrabajador(PaetTrTrabajador paetTrTrabajador) {
        this.paetTrTrabajador = paetTrTrabajador;
    }
    public PaetDsDistrito getPaetDsDistrito() {
        return this.paetDsDistrito;
    }
    
    public void setPaetDsDistrito(PaetDsDistrito paetDsDistrito) {
        this.paetDsDistrito = paetDsDistrito;
    }
    public String getDfDireccion() {
        return this.dfDireccion;
    }
    
    public void setDfDireccion(String dfDireccion) {
        this.dfDireccion = dfDireccion;
    }
    public char getDfEstado() {
        return this.dfEstado;
    }
    
    public void setDfEstado(char dfEstado) {
        this.dfEstado = dfEstado;
    }




}


