package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PaetPfProcesoFinalizacion generated by hbm2java
 */
public class PaetPfProcesoFinalizacion  implements java.io.Serializable {


     private BigDecimal pfCodigo;
     private PaetEsEstado paetEsEstado;
     private Date pfFecha;
     private String pfObservacion;

    public PaetPfProcesoFinalizacion() {
    }

	
    public PaetPfProcesoFinalizacion(BigDecimal pfCodigo, PaetEsEstado paetEsEstado, Date pfFecha) {
        this.pfCodigo = pfCodigo;
        this.paetEsEstado = paetEsEstado;
        this.pfFecha = pfFecha;
    }
    public PaetPfProcesoFinalizacion(BigDecimal pfCodigo, PaetEsEstado paetEsEstado, Date pfFecha, String pfObservacion) {
       this.pfCodigo = pfCodigo;
       this.paetEsEstado = paetEsEstado;
       this.pfFecha = pfFecha;
       this.pfObservacion = pfObservacion;
    }
   
    public BigDecimal getPfCodigo() {
        return this.pfCodigo;
    }
    
    public void setPfCodigo(BigDecimal pfCodigo) {
        this.pfCodigo = pfCodigo;
    }
    public PaetEsEstado getPaetEsEstado() {
        return this.paetEsEstado;
    }
    
    public void setPaetEsEstado(PaetEsEstado paetEsEstado) {
        this.paetEsEstado = paetEsEstado;
    }
    public Date getPfFecha() {
        return this.pfFecha;
    }
    
    public void setPfFecha(Date pfFecha) {
        this.pfFecha = pfFecha;
    }
    public String getPfObservacion() {
        return this.pfObservacion;
    }
    
    public void setPfObservacion(String pfObservacion) {
        this.pfObservacion = pfObservacion;
    }




}


