package PAET_DOMAIN;
// Generated 13-oct-2016 20:16:04 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetFcFactorComplementario generated by hbm2java
 */
public class PaetFcFactorComplementario  implements java.io.Serializable {


     private BigDecimal fcCodigo;
     private String fcDescripcion;
     private char fcEstado;
     private Set paetFcPtFactorPuestos = new HashSet(0);

    public PaetFcFactorComplementario() {
    }

	
    public PaetFcFactorComplementario(BigDecimal fcCodigo, String fcDescripcion, char fcEstado) {
        this.fcCodigo = fcCodigo;
        this.fcDescripcion = fcDescripcion;
        this.fcEstado = fcEstado;
    }
    public PaetFcFactorComplementario(BigDecimal fcCodigo, String fcDescripcion, char fcEstado, Set paetFcPtFactorPuestos) {
       this.fcCodigo = fcCodigo;
       this.fcDescripcion = fcDescripcion;
       this.fcEstado = fcEstado;
       this.paetFcPtFactorPuestos = paetFcPtFactorPuestos;
    }
   
    public BigDecimal getFcCodigo() {
        return this.fcCodigo;
    }
    
    public void setFcCodigo(BigDecimal fcCodigo) {
        this.fcCodigo = fcCodigo;
    }
    public String getFcDescripcion() {
        return this.fcDescripcion;
    }
    
    public void setFcDescripcion(String fcDescripcion) {
        this.fcDescripcion = fcDescripcion;
    }
    public char getFcEstado() {
        return this.fcEstado;
    }
    
    public void setFcEstado(char fcEstado) {
        this.fcEstado = fcEstado;
    }
    public Set getPaetFcPtFactorPuestos() {
        return this.paetFcPtFactorPuestos;
    }
    
    public void setPaetFcPtFactorPuestos(Set paetFcPtFactorPuestos) {
        this.paetFcPtFactorPuestos = paetFcPtFactorPuestos;
    }




}


