package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PaetDcDocumentacion generated by hbm2java
 */
public class PaetDcDocumentacion  implements java.io.Serializable {


     private BigDecimal dcCodigo;
     private String dcNombre;
     private String dcOrigen;
     private Date dcFecha;
     private char dcTipoProceso;
     private BigDecimal dcProceso;

    public PaetDcDocumentacion() {
    }

    public PaetDcDocumentacion(BigDecimal dcCodigo, String dcNombre, String dcOrigen, Date dcFecha, char dcTipoProceso, BigDecimal dcProceso) {
       this.dcCodigo = dcCodigo;
       this.dcNombre = dcNombre;
       this.dcOrigen = dcOrigen;
       this.dcFecha = dcFecha;
       this.dcTipoProceso = dcTipoProceso;
       this.dcProceso = dcProceso;
    }
   
    public BigDecimal getDcCodigo() {
        return this.dcCodigo;
    }
    
    public void setDcCodigo(BigDecimal dcCodigo) {
        this.dcCodigo = dcCodigo;
    }
    public String getDcNombre() {
        return this.dcNombre;
    }
    
    public void setDcNombre(String dcNombre) {
        this.dcNombre = dcNombre;
    }
    public String getDcOrigen() {
        return this.dcOrigen;
    }
    
    public void setDcOrigen(String dcOrigen) {
        this.dcOrigen = dcOrigen;
    }
    public Date getDcFecha() {
        return this.dcFecha;
    }
    
    public void setDcFecha(Date dcFecha) {
        this.dcFecha = dcFecha;
    }

    public char getDcTipoProceso() {
        return this.dcTipoProceso;
    }
    
    public void setDcTipoProceso(char dcTipoProceso) {
        this.dcTipoProceso = dcTipoProceso;
    }
    
    public BigDecimal getDcProceso() {
        return this.dcProceso;
    }
    
    public void setDcProceso(BigDecimal dcProceso) {
        this.dcProceso = dcProceso;
    }
}


