package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PaetPsProcesoSolicitud generated by hbm2java
 */
public class PaetPsProcesoSolicitud  implements java.io.Serializable {


     private BigDecimal psCodigo;
     private Date psFechaEntrada;
     private String psObservacion;
     private BigDecimal slSolicitud;
     private BigDecimal esEstado;
     private Date psFechaAtendido;
     private char psEstado;

    public PaetPsProcesoSolicitud() {
    }

    public PaetPsProcesoSolicitud(BigDecimal psCodigo, Date psFechaEntrada, String psObservacion, BigDecimal slSolicitud, BigDecimal esEstado, Date psFechaAtendido, char psEstado) {
       this.psCodigo = psCodigo;
       this.psFechaEntrada = psFechaEntrada;
       this.psObservacion = psObservacion;
       this.slSolicitud = slSolicitud;
       this.esEstado = esEstado;
       this.psFechaAtendido = psFechaAtendido;
       this.psEstado = psEstado;
    }
   
    public BigDecimal getPsCodigo() {
        return this.psCodigo;
    }
    
    public void setPsCodigo(BigDecimal psCodigo) {
        this.psCodigo = psCodigo;
    }
    
    public Date getPsFechaEntrada() {
        return this.psFechaEntrada;
    }
    
    public void setPsFechaEntrada(Date psFechaEntrada) {
        this.psFechaEntrada = psFechaEntrada;
    }
    public String getPsObservacion() {
        return this.psObservacion;
    }
    
    public void setPsObservacion(String psObservacion) {
        this.psObservacion = psObservacion;
    }
    public Date getPsFechaAtendido() {
        return this.psFechaAtendido;
    }
    
    public void setPsFechaAtendido(Date psFechaAtendido) {
        this.psFechaAtendido = psFechaAtendido;
    }
    public char getPsEstado() {
        return this.psEstado;
    }
    
    public void setPsEstado(char psEstado) {
        this.psEstado = psEstado;
    }
    
    public BigDecimal getSlSolicitud() {
        return this.slSolicitud;
    }
    
    public void setSlSolicitud(BigDecimal slSolicitud) {
        this.slSolicitud = slSolicitud;
    }
    
    public BigDecimal getEsEstado() {
        return this.esEstado;
    }
    
    public void setEsEstado(BigDecimal esEstado) {
        this.esEstado = esEstado;
    }
}


