package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetEtSlEquipoSolicitud generated by hbm2java
 */
public class PaetEtSlEquipoSolicitud  implements java.io.Serializable {


     private BigDecimal etSlCodigo;
     private PaetSlSolicitud paetSlSolicitud;
     private PaetEtEquipoTecnologico paetEtEquipoTecnologico;

    public PaetEtSlEquipoSolicitud() {
    }

    public PaetEtSlEquipoSolicitud(BigDecimal etSlCodigo, PaetSlSolicitud paetSlSolicitud, PaetEtEquipoTecnologico paetEtEquipoTecnologico) {
       this.etSlCodigo = etSlCodigo;
       this.paetSlSolicitud = paetSlSolicitud;
       this.paetEtEquipoTecnologico = paetEtEquipoTecnologico;
    }
   
    public BigDecimal getEtSlCodigo() {
        return this.etSlCodigo;
    }
    
    public void setEtSlCodigo(BigDecimal etSlCodigo) {
        this.etSlCodigo = etSlCodigo;
    }
    public PaetSlSolicitud getPaetSlSolicitud() {
        return this.paetSlSolicitud;
    }
    
    public void setPaetSlSolicitud(PaetSlSolicitud paetSlSolicitud) {
        this.paetSlSolicitud = paetSlSolicitud;
    }
    public PaetEtEquipoTecnologico getPaetEtEquipoTecnologico() {
        return this.paetEtEquipoTecnologico;
    }
    
    public void setPaetEtEquipoTecnologico(PaetEtEquipoTecnologico paetEtEquipoTecnologico) {
        this.paetEtEquipoTecnologico = paetEtEquipoTecnologico;
    }




}


