package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetDfDireccionFisica generated by hbm2java
 */
public class PaetDfDireccionFisica  implements java.io.Serializable {


     private BigDecimal dfCodigo;
     private String dfDireccion;
     private char dfEstado;
     private BigDecimal dsDistrito;
     private String trTrabajador;

    public PaetDfDireccionFisica() {
    }

    public PaetDfDireccionFisica(BigDecimal dfCodigo, String dfDireccion, char dfEstado, BigDecimal dsDistrito, String trTrabajador) {
       this.dfCodigo = dfCodigo;
       this.dfDireccion = dfDireccion;
       this.dfEstado = dfEstado;
       this.dsDistrito = dsDistrito;
       this.trTrabajador = trTrabajador;
    }
   
    public BigDecimal getDfCodigo() {
        return this.dfCodigo;
    }
    
    public void setDfCodigo(BigDecimal dfCodigo) {
        this.dfCodigo = dfCodigo;
    }
    
    public String getDfDireccion() {
        return this.dfDireccion;
    }
    
    public void setDfDireccion(String dfDireccion) {
        this.dfDireccion = dfDireccion;
    }
    public char getDfEstado() {
        return this.dfEstado;
    }
    
    public void setDfEstado(char dfEstado) {
        this.dfEstado = dfEstado;
    }
    
    public BigDecimal getDsDistrito() {
        return this.dsDistrito;
    }
    
    public void setDsDistrito(BigDecimal dsDistrito) {
        this.dsDistrito = dsDistrito;
    }
    
    public void setTrTrabajador(String trTrabajador) {
        this.trTrabajador = trTrabajador;
    }
    
    public String getTrTrabajador() {
        return this.trTrabajador;
    }
}


