package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetCaCaracteristica generated by hbm2java
 */
public class PaetCaCaracteristica  implements java.io.Serializable {


     private BigDecimal caCodigo;
     private String caDescripicion;
     private char caEstado;
     private Set paetAcCaActCaracts = new HashSet(0);

    public PaetCaCaracteristica() {
    }

	
    public PaetCaCaracteristica(BigDecimal caCodigo, String caDescripicion, char caEstado) {
        this.caCodigo = caCodigo;
        this.caDescripicion = caDescripicion;
        this.caEstado = caEstado;
    }
    public PaetCaCaracteristica(BigDecimal caCodigo, String caDescripicion, char caEstado, Set paetAcCaActCaracts) {
       this.caCodigo = caCodigo;
       this.caDescripicion = caDescripicion;
       this.caEstado = caEstado;
       this.paetAcCaActCaracts = paetAcCaActCaracts;
    }
   
    public BigDecimal getCaCodigo() {
        return this.caCodigo;
    }
    
    public void setCaCodigo(BigDecimal caCodigo) {
        this.caCodigo = caCodigo;
    }
    public String getCaDescripicion() {
        return this.caDescripicion;
    }
    
    public void setCaDescripicion(String caDescripicion) {
        this.caDescripicion = caDescripicion;
    }
    public char getCaEstado() {
        return this.caEstado;
    }
    
    public void setCaEstado(char caEstado) {
        this.caEstado = caEstado;
    }
    public Set getPaetAcCaActCaracts() {
        return this.paetAcCaActCaracts;
    }
    
    public void setPaetAcCaActCaracts(Set paetAcCaActCaracts) {
        this.paetAcCaActCaracts = paetAcCaActCaracts;
    }




}


