package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetAmAccionMejora generated by hbm2java
 */
public class PaetAmAccionMejora  implements java.io.Serializable {


     private BigDecimal amCodigo;
     private String amDescripcion;
     private BigDecimal evEvaluacion;

    public PaetAmAccionMejora() {
    }

    public PaetAmAccionMejora(BigDecimal amCodigo, String amDescripcion, BigDecimal evEvaluacion) {
       this.amCodigo = amCodigo;
       this.amDescripcion = amDescripcion;
       this.evEvaluacion = evEvaluacion;
    }
   
    public BigDecimal getAmCodigo() {
        return this.amCodigo;
    }
    
    public void setAmCodigo(BigDecimal amCodigo) {
        this.amCodigo = amCodigo;
    }
    
    public String getAmDescripcion() {
        return this.amDescripcion;
    }
    
    public void setAmDescripcion(String amDescripcion) {
        this.amDescripcion = amDescripcion;
    }
    
    public BigDecimal getEvEvaluacion() {
        return this.evEvaluacion;
    }
    
    public void setEvEvaluacion(BigDecimal evEvaluacion) {
        this.evEvaluacion = evEvaluacion;
    }
}


