package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * PaetGrGerencia generated by hbm2java
 */
public class PaetGrGerencia implements java.io.Serializable {

    private BigDecimal grCodigo;
    private String grDescripcion;
    private char grEstado;

    public PaetGrGerencia() {
    }

    public PaetGrGerencia(BigDecimal grCodigo, String grDescripcion, char grEstado) {
        this.grCodigo = grCodigo;
        this.grDescripcion = grDescripcion;
        this.grEstado = grEstado;
    }

    public BigDecimal getGrCodigo() {
        return this.grCodigo;
    }

    public void setGrCodigo(BigDecimal grCodigo) {
        this.grCodigo = grCodigo;
    }

    public String getGrDescripcion() {
        return this.grDescripcion;
    }

    public void setGrDescripcion(String grDescripcion) {
        this.grDescripcion = grDescripcion;
    }

    public char getGrEstado() {
        return this.grEstado;
    }

    public void setGrEstado(char grEstado) {
        this.grEstado = grEstado;
    }
}
