package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetPgProcesoSeguimiento generated by hbm2java
 */
public class PaetPgProcesoSeguimiento  implements java.io.Serializable {


     private BigDecimal pgCodigo;
     private PaetEsEstado paetEsEstado;
     private PaetTtTeletrabajador paetTtTeletrabajador;
     private Date pgFecha;
     private BigDecimal pgNumero;
     private String pgObservacion;
     private Date pgFechaAtendido;
     private char pgEstado;
     private Set<PaetEvEvaluacion> paetEvEvaluacions = new HashSet<PaetEvEvaluacion>(0);
     private Set<PaetReRecomendacion> paetReRecomendacions = new HashSet<PaetReRecomendacion>(0);

    public PaetPgProcesoSeguimiento() {
    }

	
    public PaetPgProcesoSeguimiento(BigDecimal pgCodigo, PaetEsEstado paetEsEstado, PaetTtTeletrabajador paetTtTeletrabajador, Date pgFecha, BigDecimal pgNumero, char pgEstado) {
        this.pgCodigo = pgCodigo;
        this.paetEsEstado = paetEsEstado;
        this.paetTtTeletrabajador = paetTtTeletrabajador;
        this.pgFecha = pgFecha;
        this.pgNumero = pgNumero;
        this.pgEstado = pgEstado;
    }
    public PaetPgProcesoSeguimiento(BigDecimal pgCodigo, PaetEsEstado paetEsEstado, PaetTtTeletrabajador paetTtTeletrabajador, Date pgFecha, BigDecimal pgNumero, String pgObservacion, Date pgFechaAtendido, char pgEstado, Set<PaetEvEvaluacion> paetEvEvaluacions, Set<PaetReRecomendacion> paetReRecomendacions) {
       this.pgCodigo = pgCodigo;
       this.paetEsEstado = paetEsEstado;
       this.paetTtTeletrabajador = paetTtTeletrabajador;
       this.pgFecha = pgFecha;
       this.pgNumero = pgNumero;
       this.pgObservacion = pgObservacion;
       this.pgFechaAtendido = pgFechaAtendido;
       this.pgEstado = pgEstado;
       this.paetEvEvaluacions = paetEvEvaluacions;
       this.paetReRecomendacions = paetReRecomendacions;
    }
   
    public BigDecimal getPgCodigo() {
        return this.pgCodigo;
    }
    
    public void setPgCodigo(BigDecimal pgCodigo) {
        this.pgCodigo = pgCodigo;
    }
    public PaetEsEstado getPaetEsEstado() {
        return this.paetEsEstado;
    }
    
    public void setPaetEsEstado(PaetEsEstado paetEsEstado) {
        this.paetEsEstado = paetEsEstado;
    }
    public PaetTtTeletrabajador getPaetTtTeletrabajador() {
        return this.paetTtTeletrabajador;
    }
    
    public void setPaetTtTeletrabajador(PaetTtTeletrabajador paetTtTeletrabajador) {
        this.paetTtTeletrabajador = paetTtTeletrabajador;
    }
    public Date getPgFecha() {
        return this.pgFecha;
    }
    
    public void setPgFecha(Date pgFecha) {
        this.pgFecha = pgFecha;
    }
    public BigDecimal getPgNumero() {
        return this.pgNumero;
    }
    
    public void setPgNumero(BigDecimal pgNumero) {
        this.pgNumero = pgNumero;
    }
    public String getPgObservacion() {
        return this.pgObservacion;
    }
    
    public void setPgObservacion(String pgObservacion) {
        this.pgObservacion = pgObservacion;
    }
    public Date getPgFechaAtendido() {
        return this.pgFechaAtendido;
    }
    
    public void setPgFechaAtendido(Date pgFechaAtendido) {
        this.pgFechaAtendido = pgFechaAtendido;
    }
    public char getPgEstado() {
        return this.pgEstado;
    }
    
    public void setPgEstado(char pgEstado) {
        this.pgEstado = pgEstado;
    }
    public Set<PaetEvEvaluacion> getPaetEvEvaluacions() {
        return this.paetEvEvaluacions;
    }
    
    public void setPaetEvEvaluacions(Set<PaetEvEvaluacion> paetEvEvaluacions) {
        this.paetEvEvaluacions = paetEvEvaluacions;
    }
    public Set<PaetReRecomendacion> getPaetReRecomendacions() {
        return this.paetReRecomendacions;
    }
    
    public void setPaetReRecomendacions(Set<PaetReRecomendacion> paetReRecomendacions) {
        this.paetReRecomendacions = paetReRecomendacions;
    }




}


