package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PaetPfProcesoSeguimiento generated by hbm2java
 */
public class PaetPfProcesoFinalizacion  implements java.io.Serializable {


     private BigDecimal pfCodigo;
     private Date pfFecha;
     private String pfObservacion;
     private BigDecimal ttTeletrabajador;
     private BigDecimal esEstado;
     private Date pfFechaAtendido;
     private char pfEstado;

    public PaetPfProcesoFinalizacion() {
    }

	
    public PaetPfProcesoFinalizacion(BigDecimal pfCodigo, Date pfFecha, String pfObservacion, BigDecimal ttTeletrabajador, BigDecimal esEstado, Date pfFechaAtendido, char pfEstado) {
        this.pfCodigo = pfCodigo;
        this.pfFecha = pfFecha;
        this.pfObservacion = pfObservacion;
        this.ttTeletrabajador = ttTeletrabajador;
        this.esEstado = esEstado;
        this.pfFechaAtendido = pfFechaAtendido;
        this.pfEstado = pfEstado;
    }
   
    public BigDecimal getPfCodigo() {
        return this.pfCodigo;
    }
    
    public void setPfCodigo(BigDecimal pfCodigo) {
        this.pfCodigo = pfCodigo;
    }
    
    public Date getPfFecha() {
        return this.pfFecha;
    }
    
    public void setPfFecha(Date pfFecha) {
        this.pfFecha = pfFecha;
    }
    
    public String getPfObservacion() {
        return this.pfObservacion;
    }
    
    public void setPfObservacion(String pfObservacion) {
        this.pfObservacion = pfObservacion;
    }
    
    public BigDecimal getTtTeletrabajador() {
        return this.ttTeletrabajador;
    }
    
    public void setTtTeletrabajador(BigDecimal ttTeletrabajador) {
        this.ttTeletrabajador = ttTeletrabajador;
    }
    
    public BigDecimal getEsEstado() {
        return this.esEstado;
    }
    
    public void setEsEstado(BigDecimal esEstado) {
        this.esEstado = esEstado;
    }
    
    public Date getPfFechaAtendido() {
        return this.pfFechaAtendido;
    }
    
    public void setPfFechaAtendido(Date pfFechaAtendido) {
        this.pfFechaAtendido = pfFechaAtendido;
    }
    public char getPfEstado() {
        return this.pfEstado;
    }
    
    public void setPfEstado(char pfEstado) {
        this.pfEstado = pfEstado;
    }
}


