package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetDvDivision generated by hbm2java
 */
public class PaetDvDivision  implements java.io.Serializable {


     private BigDecimal dvCodigo;
     private PaetGrGerencia paetGrGerencia;
     private String dvDescripcion;
     private char dvEstado;
     private BigDecimal grGerencia;
     private PaetDrDireccion paetDrDireccion;
     private Set paetPtPuestos = new HashSet(0);

    public PaetDvDivision() {
    }

	
    public PaetDvDivision(PaetGrGerencia paetGrGerencia, String dvDescripcion, char dvEstado, BigDecimal grGerencia) {
        this.paetGrGerencia = paetGrGerencia;
        this.dvDescripcion = dvDescripcion;
        this.dvEstado = dvEstado;
        this.grGerencia = grGerencia;
    }
    public PaetDvDivision(PaetGrGerencia paetGrGerencia, String dvDescripcion, char dvEstado, BigDecimal grGerencia, PaetDrDireccion paetDrDireccion, Set paetPtPuestos) {
       this.paetGrGerencia = paetGrGerencia;
       this.dvDescripcion = dvDescripcion;
       this.dvEstado = dvEstado;
       this.grGerencia = grGerencia;
       this.paetDrDireccion = paetDrDireccion;
       this.paetPtPuestos = paetPtPuestos;
    }
   
    public BigDecimal getDvCodigo() {
        return this.dvCodigo;
    }
    
    public void setDvCodigo(BigDecimal dvCodigo) {
        this.dvCodigo = dvCodigo;
    }
    public PaetGrGerencia getPaetGrGerencia() {
        return this.paetGrGerencia;
    }
    
    public void setPaetGrGerencia(PaetGrGerencia paetGrGerencia) {
        this.paetGrGerencia = paetGrGerencia;
    }
    public String getDvDescripcion() {
        return this.dvDescripcion;
    }
    
    public void setDvDescripcion(String dvDescripcion) {
        this.dvDescripcion = dvDescripcion;
    }
    public char getDvEstado() {
        return this.dvEstado;
    }
    
    public void setDvEstado(char dvEstado) {
        this.dvEstado = dvEstado;
    }
    public BigDecimal getGrGerencia() {
        return this.grGerencia;
    }
    
    public void setGrGerencia(BigDecimal grGerencia) {
        this.grGerencia = grGerencia;
    }
    public PaetDrDireccion getPaetDrDireccion() {
        return this.paetDrDireccion;
    }
    
    public void setPaetDrDireccion(PaetDrDireccion paetDrDireccion) {
        this.paetDrDireccion = paetDrDireccion;
    }
    public Set getPaetPtPuestos() {
        return this.paetPtPuestos;
    }
    
    public void setPaetPtPuestos(Set paetPtPuestos) {
        this.paetPtPuestos = paetPtPuestos;
    }




}


