package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetPtPuesto generated by hbm2java
 */
public class PaetPtPuesto  implements java.io.Serializable {

     private String ptCodigo;
     private String ptDescripcion;
     private char ptEstado;
     private BigDecimal arArea;
     private BigDecimal drDireccion;
     private BigDecimal dvDivision;
     private BigDecimal grGerencia;

    public PaetPtPuesto() {
    }

    public PaetPtPuesto(String ptCodigo, String ptDescripcion, char ptEstado, BigDecimal arArea, BigDecimal drDireccion, BigDecimal dvDivision, BigDecimal grGerencia) {
        this.ptCodigo = ptCodigo;
        this.ptDescripcion = ptDescripcion;
        this.ptEstado = ptEstado;
        this.arArea = arArea;
        this.drDireccion = drDireccion;
        this.dvDivision = dvDivision;
        this.grGerencia = grGerencia;
    }
   
    public String getPtCodigo() {
        return this.ptCodigo;
    }
    
    public void setPtCodigo(String ptCodigo) {
        this.ptCodigo = ptCodigo;
    }
    
    public String getPtDescripcion() {
        return this.ptDescripcion;
    }
    
    public void setPtDescripcion(String ptDescripcion) {
        this.ptDescripcion = ptDescripcion;
    }
    public char getPtEstado() {
        return this.ptEstado;
    }
    
    public void setPtEstado(char ptEstado) {
        this.ptEstado = ptEstado;
    }
    
    public BigDecimal getArArea() {
        return this.arArea;
    }
    
    public void setArArea(BigDecimal arArea) {
        this.arArea = arArea;
    }
    
    public BigDecimal getDrDireccion() {
        return this.drDireccion;
    }
    
    public void setDrDireccion(BigDecimal drDireccion) {
        this.drDireccion = drDireccion;
    }
    public BigDecimal getDvDivision() {
        return this.dvDivision;
    }
    
    public void setDvDivision(BigDecimal dvDivision) {
        this.dvDivision = dvDivision;
    }
    public BigDecimal getGrGerencia() {
        return this.grGerencia;
    }
    
    public void setGrGerencia(BigDecimal grGerencia) {
        this.grGerencia = grGerencia;
    }
}


