package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetCuCausa generated by hbm2java
 */
public class PaetCuCausa  implements java.io.Serializable {


     private BigDecimal cuCodigo;
     private PaetEvEvaluacion paetEvEvaluacion;
     private String cuDescripcion;

    public PaetCuCausa() {
    }

    public PaetCuCausa(BigDecimal cuCodigo, PaetEvEvaluacion paetEvEvaluacion, String cuDescripcion) {
       this.cuCodigo = cuCodigo;
       this.paetEvEvaluacion = paetEvEvaluacion;
       this.cuDescripcion = cuDescripcion;
    }
   
    public BigDecimal getCuCodigo() {
        return this.cuCodigo;
    }
    
    public void setCuCodigo(BigDecimal cuCodigo) {
        this.cuCodigo = cuCodigo;
    }
    public PaetEvEvaluacion getPaetEvEvaluacion() {
        return this.paetEvEvaluacion;
    }
    
    public void setPaetEvEvaluacion(PaetEvEvaluacion paetEvEvaluacion) {
        this.paetEvEvaluacion = paetEvEvaluacion;
    }
    public String getCuDescripcion() {
        return this.cuDescripcion;
    }
    
    public void setCuDescripcion(String cuDescripcion) {
        this.cuDescripcion = cuDescripcion;
    }




}


