package PAET_DOMAIN;
// Generated 13-oct-2016 20:16:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaetDiDia generated by hbm2java
 */
public class PaetDiDia  implements java.io.Serializable {


     private char diCodigo;
     private String diDescripcion;
     private Set paetDiSlDiaSolicituds = new HashSet(0);

    public PaetDiDia() {
    }

	
    public PaetDiDia(char diCodigo, String diDescripcion) {
        this.diCodigo = diCodigo;
        this.diDescripcion = diDescripcion;
    }
    public PaetDiDia(char diCodigo, String diDescripcion, Set paetDiSlDiaSolicituds) {
       this.diCodigo = diCodigo;
       this.diDescripcion = diDescripcion;
       this.paetDiSlDiaSolicituds = paetDiSlDiaSolicituds;
    }
   
    public char getDiCodigo() {
        return this.diCodigo;
    }
    
    public void setDiCodigo(char diCodigo) {
        this.diCodigo = diCodigo;
    }
    public String getDiDescripcion() {
        return this.diDescripcion;
    }
    
    public void setDiDescripcion(String diDescripcion) {
        this.diDescripcion = diDescripcion;
    }
    public Set getPaetDiSlDiaSolicituds() {
        return this.paetDiSlDiaSolicituds;
    }
    
    public void setPaetDiSlDiaSolicituds(Set paetDiSlDiaSolicituds) {
        this.paetDiSlDiaSolicituds = paetDiSlDiaSolicituds;
    }




}


