package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetPsProcesoSolicitud generated by hbm2java
 */
public class PaetPsProcesoSolicitud  implements java.io.Serializable {


     private BigDecimal psCodigo;
     private PaetSlSolicitud paetSlSolicitud;
     private PaetEsEstado paetEsEstado;
     private Date psFechaEntrada;
     private String psObservacion;
     private Date pfFechaAtendido;
     private char psEstado;
     private Set<PaetAnAnalisisPuesto> paetAnAnalisisPuestos = new HashSet<PaetAnAnalisisPuesto>(0);

    public PaetPsProcesoSolicitud() {
    }

	
    public PaetPsProcesoSolicitud(BigDecimal psCodigo, PaetSlSolicitud paetSlSolicitud, PaetEsEstado paetEsEstado, Date psFechaEntrada, char psEstado) {
        this.psCodigo = psCodigo;
        this.paetSlSolicitud = paetSlSolicitud;
        this.paetEsEstado = paetEsEstado;
        this.psFechaEntrada = psFechaEntrada;
        this.psEstado = psEstado;
    }
    public PaetPsProcesoSolicitud(BigDecimal psCodigo, PaetSlSolicitud paetSlSolicitud, PaetEsEstado paetEsEstado, Date psFechaEntrada, String psObservacion, Date pfFechaAtendido, char psEstado, Set<PaetAnAnalisisPuesto> paetAnAnalisisPuestos) {
       this.psCodigo = psCodigo;
       this.paetSlSolicitud = paetSlSolicitud;
       this.paetEsEstado = paetEsEstado;
       this.psFechaEntrada = psFechaEntrada;
       this.psObservacion = psObservacion;
       this.pfFechaAtendido = pfFechaAtendido;
       this.psEstado = psEstado;
       this.paetAnAnalisisPuestos = paetAnAnalisisPuestos;
    }
   
    public BigDecimal getPsCodigo() {
        return this.psCodigo;
    }
    
    public void setPsCodigo(BigDecimal psCodigo) {
        this.psCodigo = psCodigo;
    }
    public PaetSlSolicitud getPaetSlSolicitud() {
        return this.paetSlSolicitud;
    }
    
    public void setPaetSlSolicitud(PaetSlSolicitud paetSlSolicitud) {
        this.paetSlSolicitud = paetSlSolicitud;
    }
    public PaetEsEstado getPaetEsEstado() {
        return this.paetEsEstado;
    }
    
    public void setPaetEsEstado(PaetEsEstado paetEsEstado) {
        this.paetEsEstado = paetEsEstado;
    }
    public Date getPsFechaEntrada() {
        return this.psFechaEntrada;
    }
    
    public void setPsFechaEntrada(Date psFechaEntrada) {
        this.psFechaEntrada = psFechaEntrada;
    }
    public String getPsObservacion() {
        return this.psObservacion;
    }
    
    public void setPsObservacion(String psObservacion) {
        this.psObservacion = psObservacion;
    }
    public Date getPfFechaAtendido() {
        return this.pfFechaAtendido;
    }
    
    public void setPfFechaAtendido(Date pfFechaAtendido) {
        this.pfFechaAtendido = pfFechaAtendido;
    }
    public char getPsEstado() {
        return this.psEstado;
    }
    
    public void setPsEstado(char psEstado) {
        this.psEstado = psEstado;
    }
    public Set<PaetAnAnalisisPuesto> getPaetAnAnalisisPuestos() {
        return this.paetAnAnalisisPuestos;
    }
    
    public void setPaetAnAnalisisPuestos(Set<PaetAnAnalisisPuesto> paetAnAnalisisPuestos) {
        this.paetAnAnalisisPuestos = paetAnAnalisisPuestos;
    }




}


