package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetEtSlEquipoSolicitud generated by hbm2java
 */
public class PaetEtSlEquipoSolicitud  implements java.io.Serializable {


     private BigDecimal etSlCodigo;
     private BigDecimal etEquipo;
     private BigDecimal slSolicitud;

    public PaetEtSlEquipoSolicitud() {
    }

    public PaetEtSlEquipoSolicitud(BigDecimal etSlCodigo, BigDecimal etEquipo, BigDecimal slSolicitud) {
       this.etSlCodigo = etSlCodigo;
       this.etEquipo = etEquipo;
       this.slSolicitud = slSolicitud;
    }
   
    public BigDecimal getEtSlCodigo() {
        return this.etSlCodigo;
    }
    
    public void setEtSlCodigo(BigDecimal etSlCodigo) {
        this.etSlCodigo = etSlCodigo;
    }
    
    public BigDecimal getEtEquipo() {
        return this.etEquipo;
    }
    
    public void setEtEquipo(BigDecimal etEquipo) {
        this.etEquipo = etEquipo;
    }
    
    public BigDecimal getSlSolicitud() {
        return this.slSolicitud;
    }
    
    public void setSlSolicitud(BigDecimal slSolicitud) {
        this.slSolicitud = slSolicitud;
    }
}


