package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetTtTeletrabajador generated by hbm2java
 */
public class PaetTtTeletrabajador  implements java.io.Serializable {


     private BigDecimal ttCodigo;
     private Date ttFechaInicio;
     private Date ttFechaFin;
     private char ttEstado;
     private String trTrabajador;
     private BigDecimal slSolicitud;

    public PaetTtTeletrabajador() {
    }

	
    public PaetTtTeletrabajador(BigDecimal ttCodigo, Date ttFechaInicio, Date ttFechaFin, char ttEstado, String trTrabajador, BigDecimal slSolicitud) {
        this.ttCodigo = ttCodigo;
        this.ttFechaInicio = ttFechaInicio;
        this.ttFechaFin = ttFechaFin;
        this.ttEstado = ttEstado;
        this.trTrabajador = trTrabajador;
        this.slSolicitud = slSolicitud;
    }
   
    public BigDecimal getTtCodigo() {
        return this.ttCodigo;
    }
    
    public void setTtCodigo(BigDecimal ttCodigo) {
        this.ttCodigo = ttCodigo;
    }
    
    public Date getTtFechaInicio() {
        return this.ttFechaInicio;
    }
    
    public void setTtFechaInicio(Date ttFechaInicio) {
        this.ttFechaInicio = ttFechaInicio;
    }
    public Date getTtFechaFin() {
        return this.ttFechaFin;
    }
    
    public void setTtFechaFin(Date ttFechaFin) {
        this.ttFechaFin = ttFechaFin;
    }
    public char getTtEstado() {
        return this.ttEstado;
    }
    
    public void setTtEstado(char ttEstado) {
        this.ttEstado = ttEstado;
    }
    
    public String getTrTrabajador() {
        return this.trTrabajador;
    }
    
    public void setTrTrabajador(String trTrabajador) {
        this.trTrabajador = trTrabajador;
    }
    
    public BigDecimal getSlSolicitud() {
        return this.slSolicitud;
    }
    
    public void setSlSolicitud(BigDecimal slSolicitud) {
        this.slSolicitud = slSolicitud;
    }
}


