package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetDiTtDiaTeletrabajador generated by hbm2java
 */
public class PaetDiTtDiaTeletrabajador  implements java.io.Serializable {


     private BigDecimal diTtCodigo;
     private char diTtEstado;
     private char diDia;
     private BigDecimal ttTeletrabajador;

    public PaetDiTtDiaTeletrabajador() {
    }

    public PaetDiTtDiaTeletrabajador(BigDecimal diTtCodigo, char diTtEstado, char diDia, BigDecimal ttTeletrabajador) {
       this.diTtCodigo = diTtCodigo;
       this.diTtEstado = diTtEstado;
       this.diDia = diDia;
       this.ttTeletrabajador = ttTeletrabajador;
    }
   
    public BigDecimal getDiTtCodigo() {
        return this.diTtCodigo;
    }
    
    public void setDiTtCodigo(BigDecimal diTtCodigo) {
        this.diTtCodigo = diTtCodigo;
    }
    
    public char getDiTtEstado() {
        return this.diTtEstado;
    }
    
    public void setDiTtEstado(char diTtEstado) {
        this.diTtEstado = diTtEstado;
    }

    public char getDiDia() {
        return this.diDia;
    }
    
    public void setDiDia(char diDia) {
        this.diDia = diDia;
    }
    
    public BigDecimal getTtTeletrabajador() {
        return this.ttTeletrabajador;
    }
    
    public void setTtTeletrabajador(BigDecimal ttTeletrabajador) {
        this.ttTeletrabajador = ttTeletrabajador;
    }
}


