package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetTrTrabajador generated by hbm2java
 */
public class PaetTrTrabajador  implements java.io.Serializable {


     private String trUsuario;
     private PaetPtPuesto paetPtPuesto;
     private PaetTrTrabajador paetTrTrabajador;
     private String trCedula;
     private String trNombre;
     private String trApellido1;
     private String trApellido2;
     private String trSexo;
     private Date trFechaIngreso;
     private char trEstado;
     private Date trPtFechaEntrada;
     private Set paetTrTrabajadors = new HashSet(0);
     private Set paetTlTelefonos = new HashSet(0);
     private Set paetDrDireccions = new HashSet(0);
     private Set paetCrCorreos = new HashSet(0);
     private Set paetTtTeletrabajadors = new HashSet(0);
     private Set paetSlSolicituds = new HashSet(0);
     private Set paetDfDireccionFisicas = new HashSet(0);

    public PaetTrTrabajador() {
    }

	
    public PaetTrTrabajador(String trUsuario, PaetPtPuesto paetPtPuesto, String trCedula, String trNombre, String trApellido1, String trSexo, Date trFechaIngreso, char trEstado, Date trPtFechaEntrada) {
        this.trUsuario = trUsuario;
        this.paetPtPuesto = paetPtPuesto;
        this.trCedula = trCedula;
        this.trNombre = trNombre;
        this.trApellido1 = trApellido1;
        this.trSexo = trSexo;
        this.trFechaIngreso = trFechaIngreso;
        this.trEstado = trEstado;
        this.trPtFechaEntrada = trPtFechaEntrada;
    }
    public PaetTrTrabajador(String trUsuario, PaetPtPuesto paetPtPuesto, PaetTrTrabajador paetTrTrabajador, String trCedula, String trNombre, String trApellido1, String trApellido2, String trSexo, Date trFechaIngreso, char trEstado, Date trPtFechaEntrada, Set paetTrTrabajadors, Set paetTlTelefonos, Set paetDrDireccions, Set paetCrCorreos, Set paetTtTeletrabajadors, Set paetSlSolicituds, Set paetDfDireccionFisicas) {
       this.trUsuario = trUsuario;
       this.paetPtPuesto = paetPtPuesto;
       this.paetTrTrabajador = paetTrTrabajador;
       this.trCedula = trCedula;
       this.trNombre = trNombre;
       this.trApellido1 = trApellido1;
       this.trApellido2 = trApellido2;
       this.trSexo = trSexo;
       this.trFechaIngreso = trFechaIngreso;
       this.trEstado = trEstado;
       this.trPtFechaEntrada = trPtFechaEntrada;
       this.paetTrTrabajadors = paetTrTrabajadors;
       this.paetTlTelefonos = paetTlTelefonos;
       this.paetDrDireccions = paetDrDireccions;
       this.paetCrCorreos = paetCrCorreos;
       this.paetTtTeletrabajadors = paetTtTeletrabajadors;
       this.paetSlSolicituds = paetSlSolicituds;
       this.paetDfDireccionFisicas = paetDfDireccionFisicas;
    }
   
    public String getTrUsuario() {
        return this.trUsuario;
    }
    
    public void setTrUsuario(String trUsuario) {
        this.trUsuario = trUsuario;
    }
    public PaetPtPuesto getPaetPtPuesto() {
        return this.paetPtPuesto;
    }
    
    public void setPaetPtPuesto(PaetPtPuesto paetPtPuesto) {
        this.paetPtPuesto = paetPtPuesto;
    }
    public PaetTrTrabajador getPaetTrTrabajador() {
        return this.paetTrTrabajador;
    }
    
    public void setPaetTrTrabajador(PaetTrTrabajador paetTrTrabajador) {
        this.paetTrTrabajador = paetTrTrabajador;
    }
    public String getTrCedula() {
        return this.trCedula;
    }
    
    public void setTrCedula(String trCedula) {
        this.trCedula = trCedula;
    }
    public String getTrNombre() {
        return this.trNombre;
    }
    
    public void setTrNombre(String trNombre) {
        this.trNombre = trNombre;
    }
    public String getTrApellido1() {
        return this.trApellido1;
    }
    
    public void setTrApellido1(String trApellido1) {
        this.trApellido1 = trApellido1;
    }
    public String getTrApellido2() {
        return this.trApellido2;
    }
    
    public void setTrApellido2(String trApellido2) {
        this.trApellido2 = trApellido2;
    }
    public String getTrSexo() {
        return this.trSexo;
    }
    
    public void setTrSexo(String trSexo) {
        this.trSexo = trSexo;
    }
    public Date getTrFechaIngreso() {
        return this.trFechaIngreso;
    }
    
    public void setTrFechaIngreso(Date trFechaIngreso) {
        this.trFechaIngreso = trFechaIngreso;
    }
    public char getTrEstado() {
        return this.trEstado;
    }
    
    public void setTrEstado(char trEstado) {
        this.trEstado = trEstado;
    }
    public Date getTrPtFechaEntrada() {
        return this.trPtFechaEntrada;
    }
    
    public void setTrPtFechaEntrada(Date trPtFechaEntrada) {
        this.trPtFechaEntrada = trPtFechaEntrada;
    }
    public Set getPaetTrTrabajadors() {
        return this.paetTrTrabajadors;
    }
    
    public void setPaetTrTrabajadors(Set paetTrTrabajadors) {
        this.paetTrTrabajadors = paetTrTrabajadors;
    }
    public Set getPaetTlTelefonos() {
        return this.paetTlTelefonos;
    }
    
    public void setPaetTlTelefonos(Set paetTlTelefonos) {
        this.paetTlTelefonos = paetTlTelefonos;
    }
    public Set getPaetDrDireccions() {
        return this.paetDrDireccions;
    }
    
    public void setPaetDrDireccions(Set paetDrDireccions) {
        this.paetDrDireccions = paetDrDireccions;
    }
    public Set getPaetCrCorreos() {
        return this.paetCrCorreos;
    }
    
    public void setPaetCrCorreos(Set paetCrCorreos) {
        this.paetCrCorreos = paetCrCorreos;
    }
    public Set getPaetTtTeletrabajadors() {
        return this.paetTtTeletrabajadors;
    }
    
    public void setPaetTtTeletrabajadors(Set paetTtTeletrabajadors) {
        this.paetTtTeletrabajadors = paetTtTeletrabajadors;
    }
    public Set getPaetSlSolicituds() {
        return this.paetSlSolicituds;
    }
    
    public void setPaetSlSolicituds(Set paetSlSolicituds) {
        this.paetSlSolicituds = paetSlSolicituds;
    }
    public Set getPaetDfDireccionFisicas() {
        return this.paetDfDireccionFisicas;
    }
    
    public void setPaetDfDireccionFisicas(Set paetDfDireccionFisicas) {
        this.paetDfDireccionFisicas = paetDfDireccionFisicas;
    }




}


