package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetFcFactorComplementario generated by hbm2java
 */
public class PaetFcFactorComplementario  implements java.io.Serializable {


     private BigDecimal fcCodigo;
     private String fcDescripcion;
     private char fcEstado;

    public PaetFcFactorComplementario() {
    }

	
    public PaetFcFactorComplementario(BigDecimal fcCodigo, String fcDescripcion, char fcEstado) {
        this.fcCodigo = fcCodigo;
        this.fcDescripcion = fcDescripcion;
        this.fcEstado = fcEstado;
    }
   
    public BigDecimal getFcCodigo() {
        return this.fcCodigo;
    }
    
    public void setFcCodigo(BigDecimal fcCodigo) {
        this.fcCodigo = fcCodigo;
    }
    public String getFcDescripcion() {
        return this.fcDescripcion;
    }
    
    public void setFcDescripcion(String fcDescripcion) {
        this.fcDescripcion = fcDescripcion;
    }
    public char getFcEstado() {
        return this.fcEstado;
    }
    
    public void setFcEstado(char fcEstado) {
        this.fcEstado = fcEstado;
    }




}


