package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetDiSlDiaSolicitud generated by hbm2java
 */
public class PaetDiSlDiaSolicitud  implements java.io.Serializable {


     private BigDecimal diSlCodigo;
     private PaetDiDia paetDiDia;
     private PaetSlSolicitud paetSlSolicitud;

    public PaetDiSlDiaSolicitud() {
    }

    public PaetDiSlDiaSolicitud(BigDecimal diSlCodigo, PaetDiDia paetDiDia, PaetSlSolicitud paetSlSolicitud) {
       this.diSlCodigo = diSlCodigo;
       this.paetDiDia = paetDiDia;
       this.paetSlSolicitud = paetSlSolicitud;
    }
   
    public BigDecimal getDiSlCodigo() {
        return this.diSlCodigo;
    }
    
    public void setDiSlCodigo(BigDecimal diSlCodigo) {
        this.diSlCodigo = diSlCodigo;
    }
    public PaetDiDia getPaetDiDia() {
        return this.paetDiDia;
    }
    
    public void setPaetDiDia(PaetDiDia paetDiDia) {
        this.paetDiDia = paetDiDia;
    }
    public PaetSlSolicitud getPaetSlSolicitud() {
        return this.paetSlSolicitud;
    }
    
    public void setPaetSlSolicitud(PaetSlSolicitud paetSlSolicitud) {
        this.paetSlSolicitud = paetSlSolicitud;
    }




}


