package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetTrTrabajador generated by hbm2java
 */
public class PaetTrTrabajador  implements java.io.Serializable {


     private String trUsuario;
     private String trCedula;
     private String trNombre;
     private String trApellido1;
     private String trApellido2;
     private String trSexo;
     private Date trFechaIngreso;
     private char trEstado;
     private Date trPtFechaEntrada;
     private String trJefatura;
     private String ptPuesto;

    public PaetTrTrabajador() {
    }

	
    public PaetTrTrabajador(String trUsuario, String trCedula, String trNombre, String trApellido1, String trSexo, Date trFechaIngreso, char trEstado, Date trPtFechaEntrada, String trJefatura, String ptPuesto) {
        this.trUsuario = trUsuario;
        this.trCedula = trCedula;
        this.trNombre = trNombre;
        this.trApellido1 = trApellido1;
        this.trSexo = trSexo;
        this.trFechaIngreso = trFechaIngreso;
        this.trEstado = trEstado;
        this.trPtFechaEntrada = trPtFechaEntrada;
        this.trJefatura = trJefatura;
        this.ptPuesto = ptPuesto;
    }
   
    public String getTrUsuario() {
        return this.trUsuario;
    }
    
    public void setTrUsuario(String trUsuario) {
        this.trUsuario = trUsuario;
    }
    
    public String getTrCedula() {
        return this.trCedula;
    }
    
    public void setTrCedula(String trCedula) {
        this.trCedula = trCedula;
    }
    public String getTrNombre() {
        return this.trNombre;
    }
    
    public void setTrNombre(String trNombre) {
        this.trNombre = trNombre;
    }
    public String getTrApellido1() {
        return this.trApellido1;
    }
    
    public void setTrApellido1(String trApellido1) {
        this.trApellido1 = trApellido1;
    }
    public String getTrApellido2() {
        return this.trApellido2;
    }
    
    public void setTrApellido2(String trApellido2) {
        this.trApellido2 = trApellido2;
    }
    
    public String getTrSexo() {
        return this.trSexo;
    }
    
    public void setTrSexo(String trSexo) {
        this.trSexo = trSexo;
    }
    
    public Date getTrFechaIngreso() {
        return this.trFechaIngreso;
    }
    
    public void setTrFechaIngreso(Date trFechaIngreso) {
        this.trFechaIngreso = trFechaIngreso;
    }
    
    public char getTrEstado() {
        return this.trEstado;
    }
    
    public void setTrEstado(char trEstado) {
        this.trEstado = trEstado;
    }
    public Date getTrPtFechaEntrada() {
        return this.trPtFechaEntrada;
    }
    
    public void setTrPtFechaEntrada(Date trPtFechaEntrada) {
        this.trPtFechaEntrada = trPtFechaEntrada;
    }
    
    public void setTrJefatura(String trJefatura) {
        this.trJefatura = trJefatura;
    }
    
    public String getTrJefatura() {
        return this.trJefatura;
    }
    
    public void setPtPuesto(String ptPuesto) {
        this.ptPuesto = ptPuesto;
    }
    
    public String getPtPuesto() {
        return this.ptPuesto;
    }
}


