package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaetDsDistrito generated by hbm2java
 */
public class PaetDsDistrito  implements java.io.Serializable {


     private int dsCodigo;
     private String dsDescripcion;
     private short cnCanton;

    public PaetDsDistrito() {
    }

    public PaetDsDistrito(int dsCodigo, String dsDescripcion, short cnCanton) {
        this.dsCodigo = dsCodigo;
        this.dsDescripcion = dsDescripcion;
        this.cnCanton = cnCanton;
    }
   
    public void setDsCodigo(int dsCodigo) {
        this.dsCodigo = dsCodigo;
    }
    
    public int getDsCodigo() {
        return this.dsCodigo;
    }
    
    public void setDsDescripcion(String dsDescripcion) {
        this.dsDescripcion = dsDescripcion;
    }
    
    public String getDsDescripcion() {
        return this.dsDescripcion;
    }
    
    public void setCnCanton(short cnCanton) {
        this.cnCanton = cnCanton;
    }
    
    public short getCnCanton() {
        return this.cnCanton;
    }
}


