package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetFcPtFactorPuesto generated by hbm2java
 */
public class PaetFcPtFactorPuesto  implements java.io.Serializable {


     private BigDecimal fcPtCodigo;
     private PaetPtPuesto paetPtPuesto;
     private PaetFcFactorComplementario paetFcFactorComplementario;
     private boolean fcPtGrado;

    public PaetFcPtFactorPuesto() {
    }

    public PaetFcPtFactorPuesto(BigDecimal fcPtCodigo, PaetPtPuesto paetPtPuesto, PaetFcFactorComplementario paetFcFactorComplementario, boolean fcPtGrado) {
       this.fcPtCodigo = fcPtCodigo;
       this.paetPtPuesto = paetPtPuesto;
       this.paetFcFactorComplementario = paetFcFactorComplementario;
       this.fcPtGrado = fcPtGrado;
    }
   
    public BigDecimal getFcPtCodigo() {
        return this.fcPtCodigo;
    }
    
    public void setFcPtCodigo(BigDecimal fcPtCodigo) {
        this.fcPtCodigo = fcPtCodigo;
    }
    public PaetPtPuesto getPaetPtPuesto() {
        return this.paetPtPuesto;
    }
    
    public void setPaetPtPuesto(PaetPtPuesto paetPtPuesto) {
        this.paetPtPuesto = paetPtPuesto;
    }
    public PaetFcFactorComplementario getPaetFcFactorComplementario() {
        return this.paetFcFactorComplementario;
    }
    
    public void setPaetFcFactorComplementario(PaetFcFactorComplementario paetFcFactorComplementario) {
        this.paetFcFactorComplementario = paetFcFactorComplementario;
    }
    public boolean isFcPtGrado() {
        return this.fcPtGrado;
    }
    
    public void setFcPtGrado(boolean fcPtGrado) {
        this.fcPtGrado = fcPtGrado;
    }




}


