package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PaetPfProcesoFinalizacion generated by hbm2java
 */
public class PaetPfProcesoFinalizacion  implements java.io.Serializable {


     private BigDecimal pfCodigo;
     private PaetEsEstado paetEsEstado;
     private Date pfFecha;
     private String pfObservacion;
     private Date pfFechaAtendido;
     private char pfEstado;

    public PaetPfProcesoFinalizacion() {
    }

	
    public PaetPfProcesoFinalizacion(BigDecimal pfCodigo, PaetEsEstado paetEsEstado, Date pfFecha, char pfEstado) {
        this.pfCodigo = pfCodigo;
        this.paetEsEstado = paetEsEstado;
        this.pfFecha = pfFecha;
        this.pfEstado = pfEstado;
    }
    public PaetPfProcesoFinalizacion(BigDecimal pfCodigo, PaetEsEstado paetEsEstado, Date pfFecha, String pfObservacion, Date pfFechaAtendido, char pfEstado) {
       this.pfCodigo = pfCodigo;
       this.paetEsEstado = paetEsEstado;
       this.pfFecha = pfFecha;
       this.pfObservacion = pfObservacion;
       this.pfFechaAtendido = pfFechaAtendido;
       this.pfEstado = pfEstado;
    }
   
    public BigDecimal getPfCodigo() {
        return this.pfCodigo;
    }
    
    public void setPfCodigo(BigDecimal pfCodigo) {
        this.pfCodigo = pfCodigo;
    }
    public PaetEsEstado getPaetEsEstado() {
        return this.paetEsEstado;
    }
    
    public void setPaetEsEstado(PaetEsEstado paetEsEstado) {
        this.paetEsEstado = paetEsEstado;
    }
    public Date getPfFecha() {
        return this.pfFecha;
    }
    
    public void setPfFecha(Date pfFecha) {
        this.pfFecha = pfFecha;
    }
    public String getPfObservacion() {
        return this.pfObservacion;
    }
    
    public void setPfObservacion(String pfObservacion) {
        this.pfObservacion = pfObservacion;
    }
    public Date getPfFechaAtendido() {
        return this.pfFechaAtendido;
    }
    
    public void setPfFechaAtendido(Date pfFechaAtendido) {
        this.pfFechaAtendido = pfFechaAtendido;
    }
    public char getPfEstado() {
        return this.pfEstado;
    }
    
    public void setPfEstado(char pfEstado) {
        this.pfEstado = pfEstado;
    }




}


