package PAET_DOMAIN;
// Generated 13-oct-2016 20:16:04 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetDiTlDiaTeletrabajador generated by hbm2java
 */
public class PaetDiTlDiaTeletrabajador  implements java.io.Serializable {


     private BigDecimal diTlCodigo;
     private char diTlEstado;
     private char diDia;
     private String tlTeletrabajador;

    public PaetDiTlDiaTeletrabajador() {
    }

    public PaetDiTlDiaTeletrabajador(BigDecimal diTlCodigo, char diTlEstado, char diDia, String tlTeletrabajador) {
       this.diTlCodigo = diTlCodigo;
       this.diTlEstado = diTlEstado;
       this.diDia = diDia;
       this.tlTeletrabajador = tlTeletrabajador;
    }
   
    public BigDecimal getDiTlCodigo() {
        return this.diTlCodigo;
    }
    
    public void setDiTlCodigo(BigDecimal diTlCodigo) {
        this.diTlCodigo = diTlCodigo;
    }
    public char getDiTlEstado() {
        return this.diTlEstado;
    }
    
    public void setDiTlEstado(char diTlEstado) {
        this.diTlEstado = diTlEstado;
    }
    public char getDiDia() {
        return this.diDia;
    }
    
    public void setDiDia(char diDia) {
        this.diDia = diDia;
    }
    public String getTlTeletrabajador() {
        return this.tlTeletrabajador;
    }
    
    public void setTlTeletrabajador(String tlTeletrabajador) {
        this.tlTeletrabajador = tlTeletrabajador;
    }




}


