package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PaetReRecomendacion generated by hbm2java
 */
public class PaetReRecomendacion  implements java.io.Serializable {


     private BigDecimal reCodigo;
     private Date reFechaLimite;
     private Date reFechaRealizada;
     private String reDescripcion;
     private char reEstado;
     private BigDecimal pgProcesoSeguimiento;

    public PaetReRecomendacion() {
    }

	
    public PaetReRecomendacion(BigDecimal reCodigo, Date reFechaLimite, Date reFechaRealizada, String reDescripcion, char reEstado, BigDecimal pgProcesoSeguimiento) {
        this.reCodigo = reCodigo;
        this.reFechaLimite = reFechaLimite;
        this.reFechaRealizada = reFechaRealizada;
        this.reDescripcion = reDescripcion;
        this.reEstado = reEstado;
        this.pgProcesoSeguimiento = pgProcesoSeguimiento;
    }
   
    public BigDecimal getReCodigo() {
        return this.reCodigo;
    }
    
    public void setReCodigo(BigDecimal reCodigo) {
        this.reCodigo = reCodigo;
    }
    
    public Date getReFechaLimite() {
        return this.reFechaLimite;
    }
    
    public void setReFechaLimite(Date reFechaLimite) {
        this.reFechaLimite = reFechaLimite;
    }
    public Date getReFechaRealizada() {
        return this.reFechaRealizada;
    }
    
    public void setReFechaRealizada(Date reFechaRealizada) {
        this.reFechaRealizada = reFechaRealizada;
    }
    public String getReDescripcion() {
        return this.reDescripcion;
    }
    
    public void setReDescripcion(String reDescripcion) {
        this.reDescripcion = reDescripcion;
    }
    public char getReEstado() {
        return this.reEstado;
    }
    
    public void setReEstado(char reEstado) {
        this.reEstado = reEstado;
    }

    public BigDecimal getPgProcesoSeguimiento() {
        return this.pgProcesoSeguimiento;
    }
    
    public void setPgProcesoSeguimiento(BigDecimal pgProcesoSeguimiento) {
        this.pgProcesoSeguimiento = pgProcesoSeguimiento;
    }
}


