package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetPtPuesto generated by hbm2java
 */
public class PaetPtPuesto  implements java.io.Serializable {


     private String ptCodigo;
     private PaetGrGerencia paetGrGerencia;
     private PaetDvDivision paetDvDivision;
     private PaetDrDireccion paetDrDireccion;
     private PaetArArea paetArArea;
     private String ptDescripcion;
     private char ptEstado;
     private BigDecimal drDireccion;
     private BigDecimal dvDivision;
     private BigDecimal grGerencia;
     private Set<PaetFcPtFactorPuesto> paetFcPtFactorPuestos = new HashSet<PaetFcPtFactorPuesto>(0);
     private Set<PaetTrTrabajador> paetTrTrabajadors = new HashSet<PaetTrTrabajador>(0);
     private Set<PaetMtPtMetaPuesto> paetMtPtMetaPuestos = new HashSet<PaetMtPtMetaPuesto>(0);
     private Set<PaetAcPtActividadPuesto> paetAcPtActividadPuestos = new HashSet<PaetAcPtActividadPuesto>(0);

    public PaetPtPuesto() {
    }

	
    public PaetPtPuesto(String ptCodigo, char ptEstado) {
        this.ptCodigo = ptCodigo;
        this.ptEstado = ptEstado;
    }
    public PaetPtPuesto(String ptCodigo, PaetGrGerencia paetGrGerencia, PaetDvDivision paetDvDivision, PaetDrDireccion paetDrDireccion, PaetArArea paetArArea, String ptDescripcion, char ptEstado, BigDecimal drDireccion, BigDecimal dvDivision, BigDecimal grGerencia, Set<PaetFcPtFactorPuesto> paetFcPtFactorPuestos, Set<PaetTrTrabajador> paetTrTrabajadors, Set<PaetMtPtMetaPuesto> paetMtPtMetaPuestos, Set<PaetAcPtActividadPuesto> paetAcPtActividadPuestos) {
       this.ptCodigo = ptCodigo;
       this.paetGrGerencia = paetGrGerencia;
       this.paetDvDivision = paetDvDivision;
       this.paetDrDireccion = paetDrDireccion;
       this.paetArArea = paetArArea;
       this.ptDescripcion = ptDescripcion;
       this.ptEstado = ptEstado;
       this.drDireccion = drDireccion;
       this.dvDivision = dvDivision;
       this.grGerencia = grGerencia;
       this.paetFcPtFactorPuestos = paetFcPtFactorPuestos;
       this.paetTrTrabajadors = paetTrTrabajadors;
       this.paetMtPtMetaPuestos = paetMtPtMetaPuestos;
       this.paetAcPtActividadPuestos = paetAcPtActividadPuestos;
    }
   
    public String getPtCodigo() {
        return this.ptCodigo;
    }
    
    public void setPtCodigo(String ptCodigo) {
        this.ptCodigo = ptCodigo;
    }
    public PaetGrGerencia getPaetGrGerencia() {
        return this.paetGrGerencia;
    }
    
    public void setPaetGrGerencia(PaetGrGerencia paetGrGerencia) {
        this.paetGrGerencia = paetGrGerencia;
    }
    public PaetDvDivision getPaetDvDivision() {
        return this.paetDvDivision;
    }
    
    public void setPaetDvDivision(PaetDvDivision paetDvDivision) {
        this.paetDvDivision = paetDvDivision;
    }
    public PaetDrDireccion getPaetDrDireccion() {
        return this.paetDrDireccion;
    }
    
    public void setPaetDrDireccion(PaetDrDireccion paetDrDireccion) {
        this.paetDrDireccion = paetDrDireccion;
    }
    public PaetArArea getPaetArArea() {
        return this.paetArArea;
    }
    
    public void setPaetArArea(PaetArArea paetArArea) {
        this.paetArArea = paetArArea;
    }
    public String getPtDescripcion() {
        return this.ptDescripcion;
    }
    
    public void setPtDescripcion(String ptDescripcion) {
        this.ptDescripcion = ptDescripcion;
    }
    public char getPtEstado() {
        return this.ptEstado;
    }
    
    public void setPtEstado(char ptEstado) {
        this.ptEstado = ptEstado;
    }
    public BigDecimal getDrDireccion() {
        return this.drDireccion;
    }
    
    public void setDrDireccion(BigDecimal drDireccion) {
        this.drDireccion = drDireccion;
    }
    public BigDecimal getDvDivision() {
        return this.dvDivision;
    }
    
    public void setDvDivision(BigDecimal dvDivision) {
        this.dvDivision = dvDivision;
    }
    public BigDecimal getGrGerencia() {
        return this.grGerencia;
    }
    
    public void setGrGerencia(BigDecimal grGerencia) {
        this.grGerencia = grGerencia;
    }
    public Set<PaetFcPtFactorPuesto> getPaetFcPtFactorPuestos() {
        return this.paetFcPtFactorPuestos;
    }
    
    public void setPaetFcPtFactorPuestos(Set<PaetFcPtFactorPuesto> paetFcPtFactorPuestos) {
        this.paetFcPtFactorPuestos = paetFcPtFactorPuestos;
    }
    public Set<PaetTrTrabajador> getPaetTrTrabajadors() {
        return this.paetTrTrabajadors;
    }
    
    public void setPaetTrTrabajadors(Set<PaetTrTrabajador> paetTrTrabajadors) {
        this.paetTrTrabajadors = paetTrTrabajadors;
    }
    public Set<PaetMtPtMetaPuesto> getPaetMtPtMetaPuestos() {
        return this.paetMtPtMetaPuestos;
    }
    
    public void setPaetMtPtMetaPuestos(Set<PaetMtPtMetaPuesto> paetMtPtMetaPuestos) {
        this.paetMtPtMetaPuestos = paetMtPtMetaPuestos;
    }
    public Set<PaetAcPtActividadPuesto> getPaetAcPtActividadPuestos() {
        return this.paetAcPtActividadPuestos;
    }
    
    public void setPaetAcPtActividadPuestos(Set<PaetAcPtActividadPuesto> paetAcPtActividadPuestos) {
        this.paetAcPtActividadPuestos = paetAcPtActividadPuestos;
    }




}


