package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetAnAnalisisPuesto generated by hbm2java
 */
public class PaetAnAnalisisPuesto  implements java.io.Serializable {


     private BigDecimal anCodigo;
     private PaetPsProcesoSolicitud paetPsProcesoSolicitud;
     private Short anResultadoFactores;
     private Short anResultadoActividades;
     private Short anResultadoFinal;

    public PaetAnAnalisisPuesto() {
    }

	
    public PaetAnAnalisisPuesto(BigDecimal anCodigo, PaetPsProcesoSolicitud paetPsProcesoSolicitud) {
        this.anCodigo = anCodigo;
        this.paetPsProcesoSolicitud = paetPsProcesoSolicitud;
    }
    public PaetAnAnalisisPuesto(BigDecimal anCodigo, PaetPsProcesoSolicitud paetPsProcesoSolicitud, Short anResultadoFactores, Short anResultadoActividades, Short anResultadoFinal) {
       this.anCodigo = anCodigo;
       this.paetPsProcesoSolicitud = paetPsProcesoSolicitud;
       this.anResultadoFactores = anResultadoFactores;
       this.anResultadoActividades = anResultadoActividades;
       this.anResultadoFinal = anResultadoFinal;
    }
   
    public BigDecimal getAnCodigo() {
        return this.anCodigo;
    }
    
    public void setAnCodigo(BigDecimal anCodigo) {
        this.anCodigo = anCodigo;
    }
    public PaetPsProcesoSolicitud getPaetPsProcesoSolicitud() {
        return this.paetPsProcesoSolicitud;
    }
    
    public void setPaetPsProcesoSolicitud(PaetPsProcesoSolicitud paetPsProcesoSolicitud) {
        this.paetPsProcesoSolicitud = paetPsProcesoSolicitud;
    }
    public Short getAnResultadoFactores() {
        return this.anResultadoFactores;
    }
    
    public void setAnResultadoFactores(Short anResultadoFactores) {
        this.anResultadoFactores = anResultadoFactores;
    }
    public Short getAnResultadoActividades() {
        return this.anResultadoActividades;
    }
    
    public void setAnResultadoActividades(Short anResultadoActividades) {
        this.anResultadoActividades = anResultadoActividades;
    }
    public Short getAnResultadoFinal() {
        return this.anResultadoFinal;
    }
    
    public void setAnResultadoFinal(Short anResultadoFinal) {
        this.anResultadoFinal = anResultadoFinal;
    }




}


