package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaetPrProvincia generated by hbm2java
 */
public class PaetPrProvincia  implements java.io.Serializable {


     private byte prCodigo;
     private String prDescripcion;
     private Set paetCnCantons = new HashSet(0);

    public PaetPrProvincia() {
    }

	
    public PaetPrProvincia(byte prCodigo, String prDescripcion) {
        this.prCodigo = prCodigo;
        this.prDescripcion = prDescripcion;
    }
    public PaetPrProvincia(byte prCodigo, String prDescripcion, Set paetCnCantons) {
       this.prCodigo = prCodigo;
       this.prDescripcion = prDescripcion;
       this.paetCnCantons = paetCnCantons;
    }
   
    public byte getPrCodigo() {
        return this.prCodigo;
    }
    
    public void setPrCodigo(byte prCodigo) {
        this.prCodigo = prCodigo;
    }
    public String getPrDescripcion() {
        return this.prDescripcion;
    }
    
    public void setPrDescripcion(String prDescripcion) {
        this.prDescripcion = prDescripcion;
    }
    public Set getPaetCnCantons() {
        return this.paetCnCantons;
    }
    
    public void setPaetCnCantons(Set paetCnCantons) {
        this.paetCnCantons = paetCnCantons;
    }




}


