package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaetDiDia generated by hbm2java
 */
public class PaetDiDia  implements java.io.Serializable {


     private char diCodigo;
     private String diDescripcion;

    public PaetDiDia() {
    }

	
    public PaetDiDia(char diCodigo, String diDescripcion) {
        this.diCodigo = diCodigo;
        this.diDescripcion = diDescripcion;
    }
    public PaetDiDia(char diCodigo, String diDescripcion, Set<PaetDiTtDiaTeletrabajador> paetDiTtDiaTeletrabajadors) {
       this.diCodigo = diCodigo;
       this.diDescripcion = diDescripcion;
    }
   
    public char getDiCodigo() {
        return this.diCodigo;
    }
    
    public void setDiCodigo(char diCodigo) {
        this.diCodigo = diCodigo;
    }
    public String getDiDescripcion() {
        return this.diDescripcion;
    }
    
    public void setDiDescripcion(String diDescripcion) {
        this.diDescripcion = diDescripcion;
    }
}


