package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetSlSolicitud generated by hbm2java
 */
public class PaetSlSolicitud  implements java.io.Serializable {


     private BigDecimal slCodigo;
     private PaetTrTrabajador paetTrTrabajador;
     private String slJustificacion;
     private Date slFecha;
     private char slModalidad;
     private String slTiempo;
     private char slConectividad;
     private char slTelefonia;
     private char slResultado;
     private Set paetEtSlEquipoSolicituds = new HashSet(0);
     private Set paetPsProcesoSolicituds = new HashSet(0);
     private Set paetDiSlDiaSolicituds = new HashSet(0);
     private Set paetTtTeletrabajadors = new HashSet(0);

    public PaetSlSolicitud() {
    }

	
    public PaetSlSolicitud(BigDecimal slCodigo, PaetTrTrabajador paetTrTrabajador, String slJustificacion, Date slFecha, char slModalidad, String slTiempo, char slConectividad, char slTelefonia, char slResultado) {
        this.slCodigo = slCodigo;
        this.paetTrTrabajador = paetTrTrabajador;
        this.slJustificacion = slJustificacion;
        this.slFecha = slFecha;
        this.slModalidad = slModalidad;
        this.slTiempo = slTiempo;
        this.slConectividad = slConectividad;
        this.slTelefonia = slTelefonia;
        this.slResultado = slResultado;
    }
    public PaetSlSolicitud(BigDecimal slCodigo, PaetTrTrabajador paetTrTrabajador, String slJustificacion, Date slFecha, char slModalidad, String slTiempo, char slConectividad, char slTelefonia, char slResultado, Set paetEtSlEquipoSolicituds, Set paetPsProcesoSolicituds, Set paetDiSlDiaSolicituds, Set paetTtTeletrabajadors) {
       this.slCodigo = slCodigo;
       this.paetTrTrabajador = paetTrTrabajador;
       this.slJustificacion = slJustificacion;
       this.slFecha = slFecha;
       this.slModalidad = slModalidad;
       this.slTiempo = slTiempo;
       this.slConectividad = slConectividad;
       this.slTelefonia = slTelefonia;
       this.slResultado = slResultado;
       this.paetEtSlEquipoSolicituds = paetEtSlEquipoSolicituds;
       this.paetPsProcesoSolicituds = paetPsProcesoSolicituds;
       this.paetDiSlDiaSolicituds = paetDiSlDiaSolicituds;
       this.paetTtTeletrabajadors = paetTtTeletrabajadors;
    }
   
    public BigDecimal getSlCodigo() {
        return this.slCodigo;
    }
    
    public void setSlCodigo(BigDecimal slCodigo) {
        this.slCodigo = slCodigo;
    }
    public PaetTrTrabajador getPaetTrTrabajador() {
        return this.paetTrTrabajador;
    }
    
    public void setPaetTrTrabajador(PaetTrTrabajador paetTrTrabajador) {
        this.paetTrTrabajador = paetTrTrabajador;
    }
    public String getSlJustificacion() {
        return this.slJustificacion;
    }
    
    public void setSlJustificacion(String slJustificacion) {
        this.slJustificacion = slJustificacion;
    }
    public Date getSlFecha() {
        return this.slFecha;
    }
    
    public void setSlFecha(Date slFecha) {
        this.slFecha = slFecha;
    }
    public char getSlModalidad() {
        return this.slModalidad;
    }
    
    public void setSlModalidad(char slModalidad) {
        this.slModalidad = slModalidad;
    }
    public String getSlTiempo() {
        return this.slTiempo;
    }
    
    public void setSlTiempo(String slTiempo) {
        this.slTiempo = slTiempo;
    }
    public char getSlConectividad() {
        return this.slConectividad;
    }
    
    public void setSlConectividad(char slConectividad) {
        this.slConectividad = slConectividad;
    }
    public char getSlTelefonia() {
        return this.slTelefonia;
    }
    
    public void setSlTelefonia(char slTelefonia) {
        this.slTelefonia = slTelefonia;
    }
    public char getSlResultado() {
        return this.slResultado;
    }
    
    public void setSlResultado(char slResultado) {
        this.slResultado = slResultado;
    }
    public Set getPaetEtSlEquipoSolicituds() {
        return this.paetEtSlEquipoSolicituds;
    }
    
    public void setPaetEtSlEquipoSolicituds(Set paetEtSlEquipoSolicituds) {
        this.paetEtSlEquipoSolicituds = paetEtSlEquipoSolicituds;
    }
    public Set getPaetPsProcesoSolicituds() {
        return this.paetPsProcesoSolicituds;
    }
    
    public void setPaetPsProcesoSolicituds(Set paetPsProcesoSolicituds) {
        this.paetPsProcesoSolicituds = paetPsProcesoSolicituds;
    }
    public Set getPaetDiSlDiaSolicituds() {
        return this.paetDiSlDiaSolicituds;
    }
    
    public void setPaetDiSlDiaSolicituds(Set paetDiSlDiaSolicituds) {
        this.paetDiSlDiaSolicituds = paetDiSlDiaSolicituds;
    }
    public Set getPaetTtTeletrabajadors() {
        return this.paetTtTeletrabajadors;
    }
    
    public void setPaetTtTeletrabajadors(Set paetTtTeletrabajadors) {
        this.paetTtTeletrabajadors = paetTtTeletrabajadors;
    }




}


