package PAET_DOMAIN;
// Generated 17-oct-2016 18:54:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaetDsDistrito generated by hbm2java
 */
public class PaetDsDistrito  implements java.io.Serializable {


     private byte dsCodigo;
     private PaetCnCanton paetCnCanton;
     private String dsDescripcion;
     private Set paetDfDireccionFisicas = new HashSet(0);

    public PaetDsDistrito() {
    }

	
    public PaetDsDistrito(byte dsCodigo, PaetCnCanton paetCnCanton, String dsDescripcion) {
        this.dsCodigo = dsCodigo;
        this.paetCnCanton = paetCnCanton;
        this.dsDescripcion = dsDescripcion;
    }
    public PaetDsDistrito(byte dsCodigo, PaetCnCanton paetCnCanton, String dsDescripcion, Set paetDfDireccionFisicas) {
       this.dsCodigo = dsCodigo;
       this.paetCnCanton = paetCnCanton;
       this.dsDescripcion = dsDescripcion;
       this.paetDfDireccionFisicas = paetDfDireccionFisicas;
    }
   
    public byte getDsCodigo() {
        return this.dsCodigo;
    }
    
    public void setDsCodigo(byte dsCodigo) {
        this.dsCodigo = dsCodigo;
    }
    public PaetCnCanton getPaetCnCanton() {
        return this.paetCnCanton;
    }
    
    public void setPaetCnCanton(PaetCnCanton paetCnCanton) {
        this.paetCnCanton = paetCnCanton;
    }
    public String getDsDescripcion() {
        return this.dsDescripcion;
    }
    
    public void setDsDescripcion(String dsDescripcion) {
        this.dsDescripcion = dsDescripcion;
    }
    public Set getPaetDfDireccionFisicas() {
        return this.paetDfDireccionFisicas;
    }
    
    public void setPaetDfDireccionFisicas(Set paetDfDireccionFisicas) {
        this.paetDfDireccionFisicas = paetDfDireccionFisicas;
    }




}


