package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaetPrProvincia generated by hbm2java
 */
public class PaetPrProvincia  implements java.io.Serializable {


     private short prCodigo;
     private String prDescripcion;

    public PaetPrProvincia() {
    }

	
    public PaetPrProvincia(short prCodigo, String prDescripcion) {
        this.prCodigo = prCodigo;
        this.prDescripcion = prDescripcion;
    }
    
    public void setPrCodigo(short prCodigo) {
        this.prCodigo = prCodigo;
    }
    
    public short getPrCodigo() {
        return this.prCodigo;
    }
    
    public void setPrDescripcion(String prDescripcion) {
        this.prDescripcion = prDescripcion;
    }
    
    public String getPrDescripcion() {
        return this.prDescripcion;
    }
}


