package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetCrCorreo generated by hbm2java
 */
public class PaetCrCorreo  implements java.io.Serializable {


     private BigDecimal crCodigo;
     private String crCorreo;
     private char crEstado;
     private String trTrabajador;

    public PaetCrCorreo() {
    }

    public PaetCrCorreo(BigDecimal crCodigo, String crCorreo, char crEstado, String trTrabajador) {
       this.crCodigo = crCodigo;
       this.crCorreo = crCorreo;
       this.crEstado = crEstado;
       this.trTrabajador = trTrabajador;
    }
   
    public BigDecimal getCrCodigo() {
        return this.crCodigo;
    }
    
    public void setCrCodigo(BigDecimal crCodigo) {
        this.crCodigo = crCodigo;
    }
    
    public String getCrCorreo() {
        return this.crCorreo;
    }
    
    public void setCrCorreo(String crCorreo) {
        this.crCorreo = crCorreo;
    }
    public char getCrEstado() {
        return this.crEstado;
    }
    
    public void setCrEstado(char crEstado) {
        this.crEstado = crEstado;
    }

    public String getTrTrabajador() {
        return this.trTrabajador;
    }
    
    public void setTrTrabajador(String trTrabajador) {
        this.trTrabajador = trTrabajador;
    }
}


