package PAET_DOMAIN;
// Generated 13-oct-2016 20:16:04 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetFcPtFactorPuesto generated by hbm2java
 */
public class PaetFcPtFactorPuesto  implements java.io.Serializable {


     private BigDecimal fcPtCodigo;
     private PaetPtPuesto paetPtPuesto;
     private PaetFcFactorComplementario paetFcFactorComplementario;
     private char fcPtEstado;

    public PaetFcPtFactorPuesto() {
    }

    public PaetFcPtFactorPuesto(BigDecimal fcPtCodigo, PaetPtPuesto paetPtPuesto, PaetFcFactorComplementario paetFcFactorComplementario, char fcPtEstado) {
       this.fcPtCodigo = fcPtCodigo;
       this.paetPtPuesto = paetPtPuesto;
       this.paetFcFactorComplementario = paetFcFactorComplementario;
       this.fcPtEstado = fcPtEstado;
    }
   
    public BigDecimal getFcPtCodigo() {
        return this.fcPtCodigo;
    }
    
    public void setFcPtCodigo(BigDecimal fcPtCodigo) {
        this.fcPtCodigo = fcPtCodigo;
    }
    public PaetPtPuesto getPaetPtPuesto() {
        return this.paetPtPuesto;
    }
    
    public void setPaetPtPuesto(PaetPtPuesto paetPtPuesto) {
        this.paetPtPuesto = paetPtPuesto;
    }
    public PaetFcFactorComplementario getPaetFcFactorComplementario() {
        return this.paetFcFactorComplementario;
    }
    
    public void setPaetFcFactorComplementario(PaetFcFactorComplementario paetFcFactorComplementario) {
        this.paetFcFactorComplementario = paetFcFactorComplementario;
    }
    public char getFcPtEstado() {
        return this.fcPtEstado;
    }
    
    public void setFcPtEstado(char fcPtEstado) {
        this.fcPtEstado = fcPtEstado;
    }




}


