package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetEtEquipoTecnologico generated by hbm2java
 */
public class PaetEtEquipoTecnologico  implements java.io.Serializable {


     private BigDecimal etCodigo;
     private String etDescripcion;
     private char etEstado;
     private Set<PaetEtSlEquipoSolicitud> paetEtSlEquipoSolicituds = new HashSet<PaetEtSlEquipoSolicitud>(0);

    public PaetEtEquipoTecnologico() {
    }

	
    public PaetEtEquipoTecnologico(BigDecimal etCodigo, String etDescripcion, char etEstado) {
        this.etCodigo = etCodigo;
        this.etDescripcion = etDescripcion;
        this.etEstado = etEstado;
    }
    public PaetEtEquipoTecnologico(BigDecimal etCodigo, String etDescripcion, char etEstado, Set<PaetEtSlEquipoSolicitud> paetEtSlEquipoSolicituds) {
       this.etCodigo = etCodigo;
       this.etDescripcion = etDescripcion;
       this.etEstado = etEstado;
       this.paetEtSlEquipoSolicituds = paetEtSlEquipoSolicituds;
    }
   
    public BigDecimal getEtCodigo() {
        return this.etCodigo;
    }
    
    public void setEtCodigo(BigDecimal etCodigo) {
        this.etCodigo = etCodigo;
    }
    public String getEtDescripcion() {
        return this.etDescripcion;
    }
    
    public void setEtDescripcion(String etDescripcion) {
        this.etDescripcion = etDescripcion;
    }
    public char getEtEstado() {
        return this.etEstado;
    }
    
    public void setEtEstado(char etEstado) {
        this.etEstado = etEstado;
    }
    public Set<PaetEtSlEquipoSolicitud> getPaetEtSlEquipoSolicituds() {
        return this.paetEtSlEquipoSolicituds;
    }
    
    public void setPaetEtSlEquipoSolicituds(Set<PaetEtSlEquipoSolicitud> paetEtSlEquipoSolicituds) {
        this.paetEtSlEquipoSolicituds = paetEtSlEquipoSolicituds;
    }




}


