package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetDrDireccion generated by hbm2java
 */
public class PaetDrDireccion  implements java.io.Serializable {


     private BigDecimal drCodigo;
     private PaetDvDivision paetDvDivision;
     private PaetTrTrabajador paetTrTrabajador;
     private String drDescripcion;
     private char drEstado;
     private BigDecimal dvDivision;
     private Set<PaetPtPuesto> paetPtPuestos = new HashSet<PaetPtPuesto>(0);
     private Set<PaetArArea> paetArAreas = new HashSet<PaetArArea>(0);

    public PaetDrDireccion() {
    }

	
    public PaetDrDireccion(PaetDvDivision paetDvDivision, PaetTrTrabajador paetTrTrabajador, String drDescripcion, char drEstado, BigDecimal dvDivision) {
        this.paetDvDivision = paetDvDivision;
        this.paetTrTrabajador = paetTrTrabajador;
        this.drDescripcion = drDescripcion;
        this.drEstado = drEstado;
        this.dvDivision = dvDivision;
    }
    public PaetDrDireccion(PaetDvDivision paetDvDivision, PaetTrTrabajador paetTrTrabajador, String drDescripcion, char drEstado, BigDecimal dvDivision, Set<PaetPtPuesto> paetPtPuestos, Set<PaetArArea> paetArAreas) {
       this.paetDvDivision = paetDvDivision;
       this.paetTrTrabajador = paetTrTrabajador;
       this.drDescripcion = drDescripcion;
       this.drEstado = drEstado;
       this.dvDivision = dvDivision;
       this.paetPtPuestos = paetPtPuestos;
       this.paetArAreas = paetArAreas;
    }
   
    public BigDecimal getDrCodigo() {
        return this.drCodigo;
    }
    
    public void setDrCodigo(BigDecimal drCodigo) {
        this.drCodigo = drCodigo;
    }
    public PaetDvDivision getPaetDvDivision() {
        return this.paetDvDivision;
    }
    
    public void setPaetDvDivision(PaetDvDivision paetDvDivision) {
        this.paetDvDivision = paetDvDivision;
    }
    public PaetTrTrabajador getPaetTrTrabajador() {
        return this.paetTrTrabajador;
    }
    
    public void setPaetTrTrabajador(PaetTrTrabajador paetTrTrabajador) {
        this.paetTrTrabajador = paetTrTrabajador;
    }
    public String getDrDescripcion() {
        return this.drDescripcion;
    }
    
    public void setDrDescripcion(String drDescripcion) {
        this.drDescripcion = drDescripcion;
    }
    public char getDrEstado() {
        return this.drEstado;
    }
    
    public void setDrEstado(char drEstado) {
        this.drEstado = drEstado;
    }
    public BigDecimal getDvDivision() {
        return this.dvDivision;
    }
    
    public void setDvDivision(BigDecimal dvDivision) {
        this.dvDivision = dvDivision;
    }
    public Set<PaetPtPuesto> getPaetPtPuestos() {
        return this.paetPtPuestos;
    }
    
    public void setPaetPtPuestos(Set<PaetPtPuesto> paetPtPuestos) {
        this.paetPtPuestos = paetPtPuestos;
    }
    public Set<PaetArArea> getPaetArAreas() {
        return this.paetArAreas;
    }
    
    public void setPaetArAreas(Set<PaetArArea> paetArAreas) {
        this.paetArAreas = paetArAreas;
    }




}


