package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetArArea generated by hbm2java
 */
public class PaetArArea  implements java.io.Serializable {


     private BigDecimal arCodigo;
     private String arDescripcion;
     private char arEstado;
     private BigDecimal drDireccion;

    public PaetArArea() {
    }

    public PaetArArea(BigDecimal arCodigo, String arDescripcion, char arEstado, BigDecimal drDireccion) {
        this.arCodigo = arCodigo;
        this.arDescripcion = arDescripcion;
        this.arEstado = arEstado;
        this.drDireccion = drDireccion;
    }
   
    public BigDecimal getArCodigo() {
        return this.arCodigo;
    }
    
    public void setArCodigo(BigDecimal arCodigo) {
        this.arCodigo = arCodigo;
    }
    
    public String getArDescripcion() {
        return this.arDescripcion;
    }
    
    public void setArDescripcion(String arDescripcion) {
        this.arDescripcion = arDescripcion;
    }
    public char getArEstado() {
        return this.arEstado;
    }
    
    public void setArEstado(char arEstado) {
        this.arEstado = arEstado;
    }
    
    public BigDecimal getDrDireccion() {
        return this.drDireccion;
    }
    
    public void setDrDireccion(BigDecimal drDireccion) {
        this.drDireccion = drDireccion;
    }
}


