package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaetCnCanton generated by hbm2java
 */
public class PaetCnCanton  implements java.io.Serializable {


     private short cnCodigo;
     private PaetPrProvincia paetPrProvincia;
     private String cnDescripcion;
     private Set<PaetDsDistrito> paetDsDistritos = new HashSet<PaetDsDistrito>(0);

    public PaetCnCanton() {
    }

	
    public PaetCnCanton(short cnCodigo, PaetPrProvincia paetPrProvincia, String cnDescripcion) {
        this.cnCodigo = cnCodigo;
        this.paetPrProvincia = paetPrProvincia;
        this.cnDescripcion = cnDescripcion;
    }
    public PaetCnCanton(short cnCodigo, PaetPrProvincia paetPrProvincia, String cnDescripcion, Set<PaetDsDistrito> paetDsDistritos) {
       this.cnCodigo = cnCodigo;
       this.paetPrProvincia = paetPrProvincia;
       this.cnDescripcion = cnDescripcion;
       this.paetDsDistritos = paetDsDistritos;
    }
   
    public short getCnCodigo() {
        return this.cnCodigo;
    }
    
    public void setCnCodigo(short cnCodigo) {
        this.cnCodigo = cnCodigo;
    }
    public PaetPrProvincia getPaetPrProvincia() {
        return this.paetPrProvincia;
    }
    
    public void setPaetPrProvincia(PaetPrProvincia paetPrProvincia) {
        this.paetPrProvincia = paetPrProvincia;
    }
    public String getCnDescripcion() {
        return this.cnDescripcion;
    }
    
    public void setCnDescripcion(String cnDescripcion) {
        this.cnDescripcion = cnDescripcion;
    }
    public Set<PaetDsDistrito> getPaetDsDistritos() {
        return this.paetDsDistritos;
    }
    
    public void setPaetDsDistritos(Set<PaetDsDistrito> paetDsDistritos) {
        this.paetDsDistritos = paetDsDistritos;
    }




}


