package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetAcCaActCaract generated by hbm2java
 */
public class PaetAcCaActCaract  implements java.io.Serializable {


     private BigDecimal acCaCodigo;
     private PaetCaCaracteristica paetCaCaracteristica;
     private PaetAcActividad paetAcActividad;
     private char acCaTeletrabajable;

    public PaetAcCaActCaract() {
    }

    public PaetAcCaActCaract(BigDecimal acCaCodigo, PaetCaCaracteristica paetCaCaracteristica, PaetAcActividad paetAcActividad, char acCaTeletrabajable) {
       this.acCaCodigo = acCaCodigo;
       this.paetCaCaracteristica = paetCaCaracteristica;
       this.paetAcActividad = paetAcActividad;
       this.acCaTeletrabajable = acCaTeletrabajable;
    }
   
    public BigDecimal getAcCaCodigo() {
        return this.acCaCodigo;
    }
    
    public void setAcCaCodigo(BigDecimal acCaCodigo) {
        this.acCaCodigo = acCaCodigo;
    }
    public PaetCaCaracteristica getPaetCaCaracteristica() {
        return this.paetCaCaracteristica;
    }
    
    public void setPaetCaCaracteristica(PaetCaCaracteristica paetCaCaracteristica) {
        this.paetCaCaracteristica = paetCaCaracteristica;
    }
    public PaetAcActividad getPaetAcActividad() {
        return this.paetAcActividad;
    }
    
    public void setPaetAcActividad(PaetAcActividad paetAcActividad) {
        this.paetAcActividad = paetAcActividad;
    }
    public char getAcCaTeletrabajable() {
        return this.acCaTeletrabajable;
    }
    
    public void setAcCaTeletrabajable(char acCaTeletrabajable) {
        this.acCaTeletrabajable = acCaTeletrabajable;
    }




}


