package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaetFcPtFactorPuesto generated by hbm2java
 */
public class PaetFcPtFactorPuesto  implements java.io.Serializable {


     private BigDecimal fcPtCodigo;
     private Short fcPtGrado;
     private BigDecimal fcFactor;
     private String ptPuesto;

    public PaetFcPtFactorPuesto() {
    }

    public PaetFcPtFactorPuesto(BigDecimal fcPtCodigo, Short fcPtGrado, BigDecimal fcFactor, String ptPuesto) {
       this.fcPtCodigo = fcPtCodigo;
       this.fcPtGrado = fcPtGrado;
       this.fcFactor = fcFactor;
       this.ptPuesto = ptPuesto;
    }
   
    public BigDecimal getFcPtCodigo() {
        return this.fcPtCodigo;
    }
    
    public void setFcPtCodigo(BigDecimal fcPtCodigo) {
        this.fcPtCodigo = fcPtCodigo;
    }
    
    public Short isFcPtGrado() {
        return this.fcPtGrado;
    }
    
    public void setFcPtGrado(Short fcPtGrado) {
        this.fcPtGrado = fcPtGrado;
    }

    public BigDecimal getFcFactor() {
        return this.fcPtCodigo;
    }
    
    public void setFcFactor(BigDecimal fcFactor) {
        this.fcFactor = fcFactor;
    }

    public String getPtPuesto() {
        return this.ptPuesto;
    }
    
    public void setPtPuesto(String ptPuesto) {
        this.ptPuesto = ptPuesto;
    }
}


