package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
/**
 * PaetSlSolicitud generated by hbm2java
 */
public class PaetSlSolicitud  implements java.io.Serializable {


     private BigDecimal slCodigo;
     private String slJustificacion;
     private String slBeneficios;
     private Date slFecha;
     private char slModalidad;
     private String slTiempo;
     private char slConectividad;
     private char slTelefonia;
     private char slResultado;
     private String trTrabajador;

    public PaetSlSolicitud() {
    }

    public PaetSlSolicitud(BigDecimal slCodigo, String slJustificacion, String slBeneficios, Date slFecha, char slModalidad, String slTiempo, char slConectividad, char slTelefonia, char slResultado, String trTrabajador) {
       this.slCodigo = slCodigo;
       this.slJustificacion = slJustificacion;
       this.slBeneficios = slBeneficios;
       this.slFecha = slFecha;
       this.slModalidad = slModalidad;
       this.slTiempo = slTiempo;
       this.slConectividad = slConectividad;
       this.slTelefonia = slTelefonia;
       this.slResultado = slResultado;
       this.trTrabajador = trTrabajador;
    }
   
    public BigDecimal getSlCodigo() {
        return this.slCodigo;
    }
    
    public void setSlCodigo(BigDecimal slCodigo) {
        this.slCodigo = slCodigo;
    }
    
    public String getSlJustificacion() {
        return this.slJustificacion;
    }
    
    public void setSlJustificacion(String slJustificacion) {
        this.slJustificacion = slJustificacion;
    }
    public String getSlBeneficios() {
        return this.slBeneficios;
    }
    
    public void setSlBeneficios(String slBeneficios) {
        this.slBeneficios = slBeneficios;
    }
    
    public Date getSlFecha() {
        return this.slFecha;
    }
    
    public void setSlFecha(Date slFecha) {
        this.slFecha = slFecha;
    }
    public char getSlModalidad() {
        return this.slModalidad;
    }
    
    public void setSlModalidad(char slModalidad) {
        this.slModalidad = slModalidad;
    }
    public String getSlTiempo() {
        return this.slTiempo;
    }
    
    public void setSlTiempo(String slTiempo) {
        this.slTiempo = slTiempo;
    }
    public char getSlConectividad() {
        return this.slConectividad;
    }
    
    public void setSlConectividad(char slConectividad) {
        this.slConectividad = slConectividad;
    }
    public char getSlTelefonia() {
        return this.slTelefonia;
    }
    
    public void setSlTelefonia(char slTelefonia) {
        this.slTelefonia = slTelefonia;
    }
    public char getSlResultado() {
        return this.slResultado;
    }
    
    public void setSlResultado(char slresultado) {
        this.slResultado = slresultado;
    }
    
    public String getTrTrabajador() {
        return this.trTrabajador;
    }
    
    public void setTrTrabajador(String trTrabajador) {
        this.trTrabajador = trTrabajador;
    }
}


