package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetEsEstado generated by hbm2java
 */
public class PaetEsEstado  implements java.io.Serializable {


     private BigDecimal esCodigo;
     private BigDecimal esSecuencia;
     private String esDescripcion;
     private char esProceso;
     private Set<PaetPgProcesoSeguimiento> paetPgProcesoSeguimientos = new HashSet<PaetPgProcesoSeguimiento>(0);
     private Set<PaetPsProcesoSolicitud> paetPsProcesoSolicituds = new HashSet<PaetPsProcesoSolicitud>(0);
     private Set<PaetPfProcesoFinalizacion> paetPfProcesoFinalizacions = new HashSet<PaetPfProcesoFinalizacion>(0);

    public PaetEsEstado() {
    }

	
    public PaetEsEstado(BigDecimal esCodigo, BigDecimal esSecuencia, String esDescripcion, char esProceso) {
        this.esCodigo = esCodigo;
        this.esSecuencia = esSecuencia;
        this.esDescripcion = esDescripcion;
        this.esProceso = esProceso;
    }
    public PaetEsEstado(BigDecimal esCodigo, BigDecimal esSecuencia, String esDescripcion, char esProceso, Set<PaetPgProcesoSeguimiento> paetPgProcesoSeguimientos, Set<PaetPsProcesoSolicitud> paetPsProcesoSolicituds, Set<PaetPfProcesoFinalizacion> paetPfProcesoFinalizacions) {
       this.esCodigo = esCodigo;
       this.esSecuencia = esSecuencia;
       this.esDescripcion = esDescripcion;
       this.esProceso = esProceso;
       this.paetPgProcesoSeguimientos = paetPgProcesoSeguimientos;
       this.paetPsProcesoSolicituds = paetPsProcesoSolicituds;
       this.paetPfProcesoFinalizacions = paetPfProcesoFinalizacions;
    }
   
    public BigDecimal getEsCodigo() {
        return this.esCodigo;
    }
    
    public void setEsCodigo(BigDecimal esCodigo) {
        this.esCodigo = esCodigo;
    }
    public BigDecimal getEsSecuencia() {
        return this.esSecuencia;
    }
    
    public void setEsSecuencia(BigDecimal esSecuencia) {
        this.esSecuencia = esSecuencia;
    }
    public String getEsDescripcion() {
        return this.esDescripcion;
    }
    
    public void setEsDescripcion(String esDescripcion) {
        this.esDescripcion = esDescripcion;
    }
    public char getEsProceso() {
        return this.esProceso;
    }
    
    public void setEsProceso(char esProceso) {
        this.esProceso = esProceso;
    }
    public Set<PaetPgProcesoSeguimiento> getPaetPgProcesoSeguimientos() {
        return this.paetPgProcesoSeguimientos;
    }
    
    public void setPaetPgProcesoSeguimientos(Set<PaetPgProcesoSeguimiento> paetPgProcesoSeguimientos) {
        this.paetPgProcesoSeguimientos = paetPgProcesoSeguimientos;
    }
    public Set<PaetPsProcesoSolicitud> getPaetPsProcesoSolicituds() {
        return this.paetPsProcesoSolicituds;
    }
    
    public void setPaetPsProcesoSolicituds(Set<PaetPsProcesoSolicitud> paetPsProcesoSolicituds) {
        this.paetPsProcesoSolicituds = paetPsProcesoSolicituds;
    }
    public Set<PaetPfProcesoFinalizacion> getPaetPfProcesoFinalizacions() {
        return this.paetPfProcesoFinalizacions;
    }
    
    public void setPaetPfProcesoFinalizacions(Set<PaetPfProcesoFinalizacion> paetPfProcesoFinalizacions) {
        this.paetPfProcesoFinalizacions = paetPfProcesoFinalizacions;
    }




}


