package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaetCnCanton generated by hbm2java
 */
public class PaetCnCanton  implements java.io.Serializable {


     private short cnCodigo;
     private String cnDescripcion;
     private short prProvincia;

    public PaetCnCanton() {
    }

    public PaetCnCanton(short cnCodigo, String cnDescripcion, short prProvincia) {
        this.cnCodigo = cnCodigo;
        this.cnDescripcion = cnDescripcion;
        this.prProvincia = prProvincia;
    }
    
    public void setCnCodigo(short cnCodigo) {
        this.cnCodigo = cnCodigo;
    }
    
    public short getCnCodigo() {
        return this.cnCodigo;
    }
    
    public void setCnDescripcion(String cnDescripcion) {
        this.cnDescripcion = cnDescripcion;
    }
    
    public String getCnDescripcion() {
        return this.cnDescripcion;
    }
    
    public void setPrProvincia(short prProvincia) {
        this.prProvincia = prProvincia;
    }
    
    public short getPrProvincia() {
        return this.prProvincia;
    }
}


