package PAET_DOMAIN;
// Generated 19-oct-2016 22:10:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PaetDvDivision generated by hbm2java
 */
public class PaetDvDivision  implements java.io.Serializable {


     private BigDecimal dvCodigo;
     private String dvDescripcion;
     private char dvEstado;
     private BigDecimal grGerencia;

    public PaetDvDivision() {
    }
    
    public PaetDvDivision(BigDecimal dvCodigo, String dvDescripcion, char dvEstado, BigDecimal grGerencia) {
        this.dvCodigo = dvCodigo;
        this.dvDescripcion = dvDescripcion;
        this.dvEstado = dvEstado;
        this.grGerencia = grGerencia;
    }
   
    public BigDecimal getDvCodigo() {
        return this.dvCodigo;
    }
    
    public void setDvCodigo(BigDecimal dvCodigo) {
        this.dvCodigo = dvCodigo;
    }
    
    public String getDvDescripcion() {
        return this.dvDescripcion;
    }
    
    public void setDvDescripcion(String dvDescripcion) {
        this.dvDescripcion = dvDescripcion;
    }
    
    public char getDvEstado() {
        return this.dvEstado;
    }
    
    public void setDvEstado(char dvEstado) {
        this.dvEstado = dvEstado;
    }
    
    public BigDecimal getGrGerencia() {
        return this.grGerencia;
    }
    
    public void setGrGerencia(BigDecimal grGerencia) {
        this.grGerencia = grGerencia;
    }
}


